### ISSUE TITLE
semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown in E2E.ipynb

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/dask-cuda#1]
Getting the follow issues when running using dask-cuda in https://github.com/rapidsai/notebooks/blob/master/mortgage/E2E.ipynb on a DGX-1:

In notebook:
```
distributed.nanny - WARNING - Worker process 47271 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47270 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47274 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47268 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47275 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47272 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47273 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 47269 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
```

In logs:
```
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/nfs/kkraus/anaconda3/envs/cudf_dev/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```
 The workers restart and work as expected, but it does this consistently.

**Comment by mrocklin** [comment]
Unfortunately I don't know what causes issues like these.  I entirely agree that it would be good to get to the bottom of them though.

If this also occurs with `LocalCluster` then you might want to raise on dask/distributed as well for greater visibility.

**Comment by kkraus14** [comment]
It only happens as work starts and unsure exactly where in the code it's occurring so it would be hard to see if it reproduces in a standard `LocalCluster` given I'm doing GPU work. I would assume it's the same as being seen here: https://github.com/dask/distributed/issues/1078 but given the complexity and nature of this code this isn't a good reproducibility case.

**Comment by kkraus14** [comment]
This looks to be something specifically in our groupby code triggering this. cc @jrhemstad if he has any top of the head ideas as to why

**Comment by jrhemstad** [comment]
> This looks to be something specifically in our groupby code triggering this. cc @jrhemstad if he has any top of the head ideas as to why

I'm definitely out of my element here. I know there's no semaphores in the C++ code, and I don't recall seeing any warnings like these back when I was doing Dask groupby's in the past.

**Comment by kkraus14** [comment]
This actually only occurs if the RMM pool allocator is enabled so cc @harrism 😅

**Comment by kkraus14** [comment]
Confirmed this occurs in manually spawning workers via `dask-worker` as well, so this is unrelated to dask-cuda.

**Comment by brando90** [comment]
> Closing this for now as issue is completely unrelated.

sorry for reviving the thread after so long. Two questions:

1. what exactly was causing your issue? 
2. How did you resolve this?
