### ISSUE TITLE
Unable to start LocalCUDACluster

### ISSUE THREAD

**Issue by steine20** [rapidsai/dask-cuda#1009]
**Describe the issue**:

Unable to start a LocalCUDACluster.  Issue started happening about 7 days ago during a GridSearch on an XGBoost model.  Prior to this, the program was working without issue.  Upon restart and attempt to initialize the LocalCUDACluster, I get the error below.  I'm working on Windows using WSL2 Ubuntu-20.04 for the rapids package and doing my coding in PyCharm in a Jupyter notebook.

/home/jstein14/miniconda3/envs/data695/lib/python3.9/site-packages/dask_cuda/utils.py:244: UserWarning: Cannot get CPU affinity for device with index 0, setting default affinity
  warnings.warn(
2022-10-08 11:46:58,410 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-08 11:46:58,410 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2022-10-08 11:46:59,099 - distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/jstein14/miniconda3/envs/data695/lib/python3.9/site-packages/distributed/core.py", line 480, in start
    await asyncio.wait_for(self.start_unsafe(), timeout=timeout)
  File "/home/jstein14/miniconda3/envs/data695/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/home/jstein14/miniconda3/envs/data695/lib/python3.9/site-packages/distributed/worker.py", line 1406, in start_unsafe
    await self._register_with_scheduler()
  File "/home/jstein14/miniconda3/envs/data695/lib/python3.9/site-packages/distributed/worker.py", line 1093, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/jstein14/miniconda3/envs/data695/lib/python3.9/site-packages/distributed/worker.py", line 1093, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/jstein14/miniconda3/envs/data695/lib/python3.9/_collections_abc.py", line 850, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration

**Minimal Complete Verifiable Example**:

```python
from dask_cuda import LocalCUDACluster()
cluster = LocalCUDACluster()
```

**Anything else we need to know?**:

This happened after letting the XGBoost Grid search run.  Nothing was updated in between running that and this issue.  The grid search seemed to fail so I cancelled the kernel and then restarted and was unable to start the cluster after that.

I tried setting up a $ dask-cuda-worker through the command line but got similar issues.  But when I opened python in WSL and started a LocalCUDACluster it seemed to work without much issue.  I got the below warning, but the cluster still started and I could plug it into my dask.distributed client.  

  warnings.warn(
/home/jstein14/miniconda3/envs/data695/lib/python3.9/site-packages/dask_cuda/utils.py:244: UserWarning: Cannot get CPU affinity for device with index 0, setting default affinity
  warnings.warn(
2022-10-08 11:55:16,666 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-08 11:55:16,666 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize

Does this point towards the nvidia drivers?  Running $nvidia-smi I get:

Sat Oct  8 11:57:13 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.75       Driver Version: 517.40       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8     5W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        32      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

**Environment**:

- Dask version: 2022.7.1
- Python version: 3.9.13
- Operating System: Windows 11 working on a WSL2 Ubuntu-20.04
- Install method (conda, pip, source): conda following documentation on the rapids installation guide

**Comment by pentschev** [comment]
My first guess would be something went wrong with your driver install, yes. It seems `nvidia-smi` and the driver version are different, which are generally part of the same package and as far as I can remember, they always match. Did this start happening after a driver upgrade?

Could you also post the complete output of `conda list`?

**Comment by steine20** [comment]
> My first guess would be something went wrong with your driver install, yes. It seems `nvidia-smi` and the driver version are different, which are generally part of the same package and as far as I can remember, they always match. Did this start happening after a driver upgrade?
> 
> Could you also post the complete output of `conda list`?

No the strange thing is that this happened after running a large grid search on an XGBoost model.  I was letting it run overnight, and after about 12 hours of running I decided to stop the kernel and attempt to approach it with less parameters.  When I went to rerun the cluster, I started getting this error.  So I was thinking something in that grid search failed and led to this issue?  These were the last few warning messages I got while running that grid search:

2022-10-03 17:06:57,313 - distributed.nanny - WARNING - Restarting worker
2022-10-03 17:06:59,717 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-03 17:06:59,718 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize

Unfortunately, I didn't run nvidia-smi after that so I'm not sure what the drivers looked like and I have since exported that WSL image and haven't reloaded it yet.  That being said, I'm able to replicate the error on any conda environment I run.  This is the "conda list" for the environment I'm running that currently is giving me the error:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.8.3            py39hb9d737c_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
anyio                     3.6.1              pyhd8ed1ab_1    conda-forge
aom                       3.5.0                h27087fc_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb9d737c_2    conda-forge
arrow-cpp                 8.0.1           py39hd3ccb9b_2_cpu    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
aws-c-cal                 0.5.11               h95a6274_0    conda-forge
aws-c-common              0.6.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
aws-c-io                  0.10.5               hfb6a706_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
boost                     1.74.0           py39h5472131_5    conda-forge
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-blosc2                  2.4.2                h7a311fb_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            ha12eb4b_1010    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39he91dace_0    conda-forge
cfitsio                   4.1.0                hd9d235c_0    conda-forge
charls                    2.3.4                h9c3ff4c_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hf3d152e_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5            py39hf939315_0    conda-forge
cryptography              38.0.1           py39hd97740a_0    conda-forge
cucim                     22.08.01        cuda_11_py39_g61500c2_0    rapidsai
cuda-python               11.7.0           py39h3fd9d12_0    nvidia
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudf                      22.08.01        cuda_11_py39_g31337c9001_0    rapidsai
cudf_kafka                22.08.01        py39_g31337c9001_0    rapidsai
cugraph                   22.08.00        cuda11_py39_g460692f0_0    rapidsai
cuml                      22.08.00        cuda11_py39_g1e2f8a9aa_0    rapidsai
cupy                      10.6.0           py39h3da55b9_0    conda-forge
curl                      7.85.0               h7bff187_0    conda-forge
cusignal                  22.08.00        py39_gf8642e3_0    rapidsai
cuspatial                 22.08.00        py39_g125c3c2_0    rapidsai
custreamz                 22.08.01        py39_g31337c9001_0    rapidsai
cuxfilter                 22.08.00        py39_gacc6d5e_0    rapidsai
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cyrus-sasl                2.1.27               h230043b_5    conda-forge
cytoolz                   0.12.0           py39hb9d737c_0    conda-forge
dask                      2022.7.1           pyhd8ed1ab_0    conda-forge
dask-core                 2022.7.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 22.08.00        py39_g9a61ce5_0    rapidsai
dask-cudf                 22.08.01        cuda_11_py39_g31337c9001_0    rapidsai
datashader                0.13.1a                    py_0    rapidsai
datashape                 0.5.4                      py_1    conda-forge
dav1d                     1.0.0                h166bdaf_1    conda-forge
debugpy                   1.6.3            py39h5a03fae_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.7.1           pyhd8ed1ab_0    conda-forge
dlpack                    0.5                  h9c3ff4c_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
faiss-proc                1.0.0                      cuda    rapidsai
fastavro                  1.6.1            py39hb9d737c_0    conda-forge
fastrlock                 0.8              py39h5a03fae_2    conda-forge
fiona                     1.8.21           py39h83acdc4_1    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
folium                    0.13.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hc2a2eb6_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.4           py39hb9d737c_0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
frozenlist                1.3.1            py39hb9d737c_0    conda-forge
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
gdal                      3.4.3            py39hc691d54_0    conda-forge
geopandas                 0.11.1             pyhd8ed1ab_0    conda-forge
geopandas-base            0.11.1             pyha770c72_0    conda-forge
geos                      3.10.2               h9c3ff4c_0    conda-forge
geotiff                   1.7.1                h509b78c_1    conda-forge
gettext                   0.19.8.1          h27087fc_1009    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
grpc-cpp                  1.47.1               hbad87ad_6    conda-forge
hdf4                      4.2.15               h9772cbc_4    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.14.6             pyhd8ed1ab_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.9.26        py39hf586f7a_0    conda-forge
imageio                   2.22.0             pyhfa7a67d_0    conda-forge
importlib-metadata        4.11.4           py39hf3d152e_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.16.0             pyh210e3f2_0    conda-forge
ipython                   8.5.0              pyh41d4057_1    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2              pyhd8ed1ab_1    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
json-c                    0.16                 hc379101_0    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-server-proxy      3.2.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39hf3d152e_0    conda-forge
jupyter_server            1.19.1             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kealib                    1.4.15               hfe1a663_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_4    conda-forge
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libavif                   0.10.1               h5cdd6b5_2    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcucim                  22.08.01        cuda11_g61500c2_0    rapidsai
libcudf                   22.08.01        cuda11_g31337c9001_0    rapidsai
libcudf_kafka             22.08.01          g31337c9001_0    rapidsai
libcugraph                22.08.00        cuda11_g460692f0_0    rapidsai
libcugraph_etl            22.08.00        cuda11_g460692f0_0    rapidsai
libcugraphops             22.08.00        cuda11_g7f764d0_0    nvidia
libcuml                   22.08.00        cuda11_g1e2f8a9aa_0    rapidsai
libcumlprims              22.08.00        cuda11_g1770e60_0    nvidia
libcurl                   7.85.0               h7bff187_0    conda-forge
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcuspatial              22.08.00        cuda11_g125c3c2_0    rapidsai
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libfaiss                  1.7.0           cuda110h8045045_8_cuda    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgdal                   3.4.3                h56144a5_0    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.74.0               h7a41b64_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libgoogle-cloud           2.1.0                h9ebe8e8_2    conda-forge
libgpg-error              1.45                 hc0c96e0_0    conda-forge
libgsasl                  1.10.0               h5b4c23d_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_4    conda-forge
libnetcdf                 4.8.1           nompi_h329d8a1_102    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libpq                     14.2                 hd57d9b9_0    conda-forge
libprotobuf               3.20.1               h6239696_4    conda-forge
libraft-distance          22.08.00        cuda11_g87a7d16c_0    rapidsai
libraft-headers           22.08.00        cuda11_g87a7d16c_0    rapidsai
libraft-nn                22.08.00        cuda11_g87a7d16c_0    rapidsai
librdkafka                1.7.0                hc49e61c_1    conda-forge
librmm                    22.08.00        cuda11_gd212232c_0    rapidsai
librttopo                 1.1.0                hf69c175_9    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libspatialite             5.0.1               ha867d66_15    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libthrift                 0.16.0               h491838f_2    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libutf8proc               2.7.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libwebp                   1.2.4                h522a892_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxgboost                1.6.0dev.rapidsai22.08       cuda_11_0    rapidsai
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.12               h166bdaf_4    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
llvmlite                  0.39.1           py39h7d9a04d_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.0.0            py39h029007f_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
matplotlib-base           3.6.0            py39hf9fd14e_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.4            py39hf939315_0    conda-forge
multidict                 6.0.2            py39hb9d737c_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.7.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.1              pyhd8ed1ab_0    conda-forge
nbformat                  5.6.1              pyhd8ed1ab_0    conda-forge
nccl                      2.14.3.1             h17a0586_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nodejs                    17.8.0               h784f1fd_0    conda-forge
notebook                  6.4.12                   pypi_0    pypi
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numba                     0.56.2           py39h61ddf18_1    conda-forge
numpy                     1.21.6           py39h18676bf_0    conda-forge
nvtx                      0.2.3            py39h3811e60_1    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
orc                       1.7.6                h6c59b99_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4            py39h1832856_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     0.12.7             pyhd8ed1ab_0    conda-forge
param                     1.12.2             pyh6c4a22f_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                hc3806b6_1    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39hd5dbb17_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
poppler                   22.04.0              h8b295ee_2    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 h2510834_0    conda-forge
proj                      9.0.0                h93bde94_1    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
protobuf                  3.20.1           py39h5a03fae_0    conda-forge
psutil                    5.9.2            py39hb9d737c_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptxcompiler               0.2.0            py39h107f55c_0    rapidsai
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-xgboost                1.6.0dev.rapidsai22.08  cuda_11_py39_0    rapidsai
pyarrow                   8.0.1           py39hc0775d8_2_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
pyee                      8.1.0              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pylibcugraph              22.08.00        cuda11_py39_g460692f0_0    rapidsai
pynvml                    11.4.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyppeteer                 1.0.2              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.1            py39hcadae2f_0    conda-forge
pyraft                    22.08.00        cuda11_py39_g87a7d16c_0    rapidsai
pyrsistent                0.18.1           py39hb9d737c_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-confluent-kafka    1.7.0            py39h3811e60_2    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.4             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.2.1              pyhd8ed1ab_1    conda-forge
pywavelets                1.3.0            py39hd257fcd_1    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
pyzmq                     24.0.1           py39headdf64_0    conda-forge
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
rapids                    22.08.00        cuda11_py39_gde726fb_114    rapidsai
rapids-xgboost            22.08.00        cuda11_py39_gde726fb_114    rapidsai
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rmm                       22.08.00        cuda11_py39_gd212232c_0    rapidsai
rtree                     1.0.0            py39hb102c33_1    conda-forge
s2n                       1.0.10               h9b69904_0    conda-forge
scikit-image              0.19.3           py39h1832856_1    conda-forge
scikit-learn              1.1.2            py39he5e8d7e_0    conda-forge
scipy                     1.9.1            py39h8ba3f38_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.10.0          py39hf3d152e_0    conda-forge
shapely                   1.8.2            py39h73b9895_1    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spdlog                    1.8.5                h4bd325d_1    conda-forge
sqlite                    3.39.4               h4ff8645_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
streamz                   0.6.4              pyh6c4a22f_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.16.0             pyh41d4057_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2022.8.12          pyhd8ed1ab_0    conda-forge
tiledb                    2.8.3                h1e4a385_1    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39hb9d737c_3    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
treelite                  2.4.0            py39h6b629c6_1    conda-forge
treelite-runtime          2.4.0                    pypi_0    pypi
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzcode                    2022d                h166bdaf_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
ucx                       1.13.1               ha0ee010_0    conda-forge
ucx-proc                  1.0.0                       gpu    rapidsai
ucx-py                    0.27.00         py39_g9abe3c1_0    rapidsai
unicodedata2              14.0.0           py39hb9d737c_1    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.4.1              pyhd8ed1ab_0    conda-forge
websockets                10.3             py39hb9d737c_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3              pyhd8ed1ab_0    conda-forge
xarray                    2022.9.0           pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h8ce2273_4    conda-forge
xgboost                   1.6.0dev.rapidsai22.08  cuda_11_py39_0    rapidsai
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xyzservices               2022.9.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2            py39hb9d737c_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zfp                       1.0.0                h27087fc_1    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_4    conda-forge
zlib-ng                   2.0.6                h166bdaf_0    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

**Comment by pentschev** [comment]
Thank you for the details. The way you're describing events makes me believe what happened is that the Dask directory was left with some "garbage" from the previous run which is now being loaded when you attempt to start a new cluster. Could you try once again to launch passing a clean directory via `local_directory`? E.g.:

```python
cluster = LocalCUDACluster(local_directory="/tmp/username/dask")
```

**Comment by pentschev** [comment]
> That worked!

Oh great!

> When I start the cluster, I still get the warning message below but it seems to not be an issue so I'm unconcerned about it. Also is there any way to clear out some of that "garbage" in the Dask Directory?

You'll have to remove the directory entirely. By default I believe there will be a `dask-worker-space` under the current working directory that you'll have to remove. This is most of the time not necessary, but it can happen if the cluster terminates unexpectedly.

> /home/jstein14/miniconda3/envs/dat_test/lib/python3.9/site-packages/dask_cuda/utils.py:244: UserWarning: Cannot get CPU affinity for device with index 0, setting default affinity

Yes, this is a known limitation on WSL2, so for now you'll see them and hopefully in the future a driver upgrade will resolve that, but there's currently no ETA on that.

**Comment by steine20** [comment]
Perfect, thank you again for the help!

**Comment by pentschev** [comment]
No problem, glad it got resolved!
