### ISSUE TITLE
Public version 22.08.00 depend on dask 2022.7.1 (must be 2022.8.1) 

### ISSUE THREAD

**Issue by pprados** [rapidsai/dask-cuda#1011]
`conda search --info dask-cuda ` describe a dependency of `dask 2022.7.1`.

The last version is dask 2022.8.1. I suppose is a mistake.

**Comment by pentschev** [comment]
This is no mistake. Dask-CUDA doesn't follow the same release schedule cycle of upstream Dask/Distributed. Before every RAPIDS release (including Dask-CUDA) we pin to a Dask stable version that has been tested.

Some additional discussions regarding this topic can be found in https://github.com/rapidsai/dask-cuda/issues/848 and https://github.com/rapidsai/dask-cuda/issues/911.
