### ISSUE TITLE
Rename `dask-config` CLI for clarity

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#1038]
Currently Dask-CUDA exposes a CLI called `dask-config`

https://github.com/rapidsai/dask-cuda/blob/2c99f5a0fdf59a7f89e182c4add9121e0b8dd48d/setup.py#L61

That points to [a similarly named module]( https://github.com/rapidsai/dask-cuda/blob/2c99f5a0fdf59a7f89e182c4add9121e0b8dd48d/dask_cuda/cli/dask_config.py )

As it may not be clear that this CLI comes from Dask-CUDA (say in a busy environment), wonder if it makes sense to rename this for clarity

**Comment by wence-** [comment]
Additionally, this is broken since the `dask_config` module doesn't advertise a `go` function.

**Comment by jakirkham** [comment]
This raises another good question. Is it being used (considering some functionality in it is currently broken and I'm guessing we are not hearing about it)?

**Comment by wence-** [comment]
It was only recently introduced, so probably no-one knows about it yet. I recommend renaming (via the new `dask` commandline tool) to `dask cuda show-cluster-config` or similar.

**Comment by quasiben** [comment]
+1 to renaming

**Comment by jakirkham** [comment]
In PR ( https://github.com/rapidsai/dask-cuda/pull/981 ), @jacobtomlinson suggested using `dask cuda config`

**Comment by jakirkham** [comment]
Did we settle on a name?

cc @quasiben

**Comment by jacobtomlinson** [comment]
Either my or @wence-'s suggestions seem fine.
