### ISSUE TITLE
Drop `pytest-asyncio`?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#1044]
Currently CI has this `pytest-asyncio` constraint

https://github.com/rapidsai/dask-cuda/blob/b3ed9029a1ad02a61eb7fbd899a5a6826bb5cfac/ci/gpu/build.sh#L73

It appears Distributed had added this constraint in PR ( https://github.com/dask/distributed/pull/4212 ), but subsequently resolved the issue by dropping `pytest-asyncio` in PR ( https://github.com/dask/distributed/pull/6063 ).

Given this, wonder if Dask-CUDA should do the same

**Comment by pentschev** [comment]
Yeah, I think this was needed but I switch it in https://github.com/rapidsai/dask-cuda/pull/1026 , from the description:

> Even though pytest-async is installed, it has not executed async tests that aren't wrapped in gen_cluster. Using gen_cluster is the proper way for Dask testing, but in few exceptions we may not be able to use it, such as when cleanup must be avoided.

Right now, I don't think `pytest-asyncio` is needed anywhere else. I'll submit a PR to remove that.
