### ISSUE TITLE
AttributeError: 'LocalCUDACluster' object has no attribute 'scheduler_port'

### ISSUE THREAD

**Issue by gfelitti** [rapidsai/dask-cuda#107]
I'm using to use dask_cuda in Pyhton 3.7 / Ubuntu 19. 

When I try to define cluster = LocalCUDACluster(), dask_cuda gives me an AttributeError with the message "AttributeError: 'LocalCUDACluster' object has no attribute 'scheduler_port'", even tough I am not calling any scheduler_port.

Any tips to solve this?

**Comment by mrocklin** [comment]
If you upgrade to git master does the problem persist?

    pip install git+https://github.com/rapidsai/dask-cuda --upgrade

**Comment by gfelitti** [comment]
It worked. Thanks
