### ISSUE TITLE
[QST] Query on dask-cuda-worker and compatibility with dask-worker

### ISSUE THREAD

**Issue by ksangeek** [rapidsai/dask-cuda#108]
I see that dask-cuda-worker and dask-worker can register and work with the same dask-scheduler, but it does not look like that the current implementation of dask-scheduler understands or differentiates these two different workers. What is the recommended (current or possibly in near future) method of these two kinds of dask-workers being used together? Or should these two kinds of workers not be used with the same scheduler?

These are some specific observations based on which this question is asked (Used dask-cuda ver 0.8.0 and dask/distributed ver 2.1.0 ) -

1. If I submit a CPU job(e.g. Loading a CSV file as dask-dataframe and perform some preprocessing) to a scheduler which only has one dask-cuda-worker(4 GPUs) then I see that the job uses CPUs. But using dask-cuda-worker for CPU jobs has restrictions as this doesn't support all the options that are available for dask-worker.
2. When I use two different machines for my experiment(both having 4 GPUs); on one(A) I start dask-cuda-worker and on another(B) dask-worker, both registered to the same scheduler. If I submit a job which requires GPU (e.g. dask-xgboost with tree_method:gpu_hist) I see that it also uses the GPU of machine B which just has dask-worker running.
3. This is more of a feature request, but I think the dask-dashboard should have special consideration for dask-cuda-worker! In fact, it shows very bizarre o/p e.g.
 when the dask-cuda-worker is using CPU and host memory (in the observation 1 above) it displays a change in memory usage though the GPU memory usage is unchanged!

In general, this query is more to understand the working expectations and design goals of dask-cuda-worker for jobs which has requirements for Host CPU/Memory as well requires GPUs for some part of the job. In the future, could dask-cuda-worker be a superset of dask-worker which in addition to having knowledge of GPUs supports all the CPU specific options available in dask-worker?

**Comment by pentschev** [comment]
> I see that dask-cuda-worker and dask-worker can register and work with the same dask-scheduler, but it does not look like that the current implementation of dask-scheduler understands or differentiates these two different workers. What is the recommended (current or possibly in near future) method of these two kinds of dask-workers being used together? Or should these two kinds of workers not be used with the same scheduler?

Indeed both will work with `dask-scheduler` and both will work with GPUs (but `dask-worker` will be limited). For instance, `dask-cuda-worker` will assign one, and only one, GPU per worker in a correct fashion, whereas `dask-worker` will simply use the first GPU. That said, I would recommend using `dask-cuda-worker` only.

> 1. If I submit a CPU job(e.g. Loading a CSV file as dask-dataframe and perform some preprocessing) to a scheduler which only has one dask-cuda-worker(4 GPUs) then I see that the job uses CPUs. But using dask-cuda-worker for CPU jobs has restrictions as this doesn't support all the options that are available for dask-worker.

Could you elaborate on which options are not supported? `dask-cuda-worker` is a specialization of `dask-worker`, and if something is not supported it's likely missing by mistake. In the past couple of months dask-distributed has been refactored quite substantially, and it could be that dask-cuda simply missed adding some options.

> 2. When I use two different machines for my experiment(both having 4 GPUs); on one(A) I start dask-cuda-worker and on another(B) dask-worker, both registered to the same scheduler. If I submit a job which requires GPU (e.g. dask-xgboost with tree_method:gpu_hist) I see that it also uses the GPU of machine B which just has dask-worker running.

I'm not sure if this is what you're trying to achieve, but at the moment we do not support hybrid setups (some workers have GPUs and others don't), the scheduler won't explicitly check workers for GPU support, and it could be that it will send GPU work for a worker without GPU and that would crash, and since also `dask-worker` supports GPU to some extent, it will end up running GPU code too.

> 3. This is more of a feature request, but I think the dask-dashboard should have special consideration for dask-cuda-worker! In fact, it shows very bizarre o/p e.g.
>    when the dask-cuda-worker is using CPU and host memory (in the observation 1 above) it displays a change in memory usage though the GPU memory usage is unchanged!

Indeed, there was not so much work on the dashboard, but this is certainly something that we want to improve eventually. I do not have a timeline for that though.

> In general, this query is more to understand the working expectations and design goals of dask-cuda-worker for jobs which has requirements for Host CPU/Memory as well requires GPUs for some part of the job. In the future, could dask-cuda-worker be a superset of dask-worker which in addition to having knowledge of GPUs supports all the CPU specific options available in dask-worker?

Yes, perhaps in the future we could refactor `dask-cuda-worker` to be a superset of `dask-worker` (in fact, the entire repo is a superset of dask-distributed). I also do not have a timeline for that, but we encourage users to contribute if something that they need is missing. So if you have the time, a PR to address that would be very welcome!

**Comment by ksangeek** [comment]
Thank you @pentschev for quick help with these questions! Follow up -

> Indeed both will work with `dask-scheduler` and both will work with GPUs (but `dask-worker` will be limited). For instance, `dask-cuda-worker` will assign one, and only one, GPU per worker in a correct fashion, whereas `dask-worker` will simply use the first GPU. That said, I would recommend using `dask-cuda-worker` only.

I see that the motivation for this package is to enable proper support for GPUs in the dask ecosystem. Could you please elaborate a bit on the benefits?

And it would really help if you could compare with what is the limitation with using GPUs with dask-worker, assuming I am using it this way ( Set CUDA_VISIBLE_DEVICE to a single GPU; and start dask-worker with `..--resources "GPU=1"` )? (ref - https://distributed.dask.org/en/latest/resources.html). The advantage of this method as I see it is that, I could have a mixed cluster with and without GPUs under the same scheduler; and if a client demands a particular job only to be submitted to a worker which has GPU resource, it would take care of that!

Unless you see a downside of this, I think it would also be a good idea of dask-cuda-worker to set GPU resource under the cover to help scheduler efficiently use resources in a hybrid cluster. (Apologies for bringing back this again even though you mentioned that currently hybrid mode is not supported, perhaps a comment for future :))

> Could you elaborate on which options are not supported? `dask-cuda-worker` is a specialization of `dask-worker`, and if something is not supported it's likely missing by mistake. In the past couple of months dask-distributed has been refactored quite substantially, and it could be that dask-cuda simply missed adding some options.

What I meant here was the flexibility to launch a separate dask-worker process per CPU core on the machine with dask-cuda-worker. It lacks the `--nprocs` option which one could have used to launch workers based on the number of CPU cores(but not necessarily always create a new process on GPU). 

Also, could you help with if the current implementation supports adaptive scaling up/down of the cuda-workers (ref - https://docs.dask.org/en/latest/setup/adaptive.html)?

**Comment by pentschev** [comment]
> I see that the motivation for this package is to enable proper support for GPUs in the dask ecosystem. Could you please elaborate a bit on the benefits?

The main benefits today are the automated launching of workers per GPU (e.g., it will launch various workers on a same machine, each on a different GPU, without requiring the user to set `CUDA_VISIBLE_DEVICES` for each new worker individually), and the support for spilling data device<->host<->disk (dask-distributed will only do host<->disk) when the data won't fit on the GPU.

> And it would really help if you could compare with what is the limitation with using GPUs with dask-worker, assuming I am using it this way ( Set CUDA_VISIBLE_DEVICE to a single GPU; and start dask-worker with ..--resources "GPU=1" )? (ref - https://distributed.dask.org/en/latest/resources.html). The advantage of this method as I see it is that, I could have a mixed cluster with and without GPUs under the same scheduler; and if a client demands a particular job only to be submitted to a worker which has GPU resource, it would take care of that!

I suppose that's reasonable, but we don't really test for that, so we don't ensure that this will work properly today.

> Unless you see a downside of this, I think it would also be a good idea of dask-cuda-worker to set GPU resource under the cover to help scheduler efficiently use resources in a hybrid cluster. (Apologies for bringing back this again even though you mentioned that currently hybrid mode is not supported, perhaps a comment for future :))

As of now there's not any work really on supporting hybrid clusters, but this may change in the future. I suspect that it will work appropriately with the solution you pointed out, but as you noted, the responsibility of labelling tasks correctly falls upon the user, so the scheduler alone won't check whether a given task will work on hybrid's cluster worker.

> What I meant here was the flexibility to launch a separate dask-worker process per CPU core on the machine with dask-cuda-worker. It lacks the --nprocs option which one could have used to launch workers based on the number of CPU cores(but not necessarily always create a new process on GPU).

Yes, indeed we don't allow that. The model that we're using for dask-cuda (and more broadly, for RAPIDS) is "one worker per GPU". You can still control the number of threads with `--nthreads`, but given that all communication between processes currently occurs through TCP, I wouldn't recommend that, but just using multiple threads instead, in that case, threads would just be able  to reach another thread's memory directly.

> Also, could you help with if the current implementation supports adaptive scaling up/down of the cuda-workers (ref - https://docs.dask.org/en/latest/setup/adaptive.html)?

I don't think anybody tried that specifically so far, but I don't see any technical constraints that would prevent that from working. However, note that as I mentioned before we're following a "one worker per GPU" model, so in dask-cuda we would normally scale up/down the amount of GPUs used, which may not be exactly what you're expecting.

**Comment by ksangeek** [comment]
Thank you @pentschev. This is all very useful information that you have compiled in here.

**Comment by pentschev** [comment]
Glad I could answer your questions @ksangeek . I just saw new comments on https://github.com/rapidsai/dask-cuda/issues/36 regarding the dashboard progress, you may want to watch that for new information, but it seems like we should have some releases in the next couple of weeks.
