### ISSUE TITLE
Dask-CUDA: CUDA 12 Conda Packages

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#1115]
Pushing for CUDA 12 Conda package builds of libraries for RAPIDS 23.04. This issue is for tracking that work.

Requirements (please recheck):

```[tasklist]
### Developer tasks
- [x] I've confirmed the list below is correct (or updated if not)
```

```[tasklist]
### Dependencies from Conda
- [ ] https://github.com/conda-forge/pynvml-feedstock/pull/11
- [ ] https://github.com/conda-forge/numba-feedstock/issues/112
```

```[tasklist]
### RAPIDS Conda dependencies
- [ ] https://github.com/rapidsai/rmm/issues/1207
- [ ] https://github.com/rapidsai/cudf/issues/12771
- [ ] https://github.com/rapidsai/kvikio/pull/224
- [ ] https://github.com/rapidsai/ucx-py/issues/927
```

```[tasklist]
### Optional dependencies from Conda
- [ ] https://github.com/conda-forge/cupy-feedstock/issues/139
- [x] nvtx (Python)
- [ ] https://github.com/conda-forge/ucx-split-feedstock/issues/116
```

**Comment by wence-** [comment]
`(via distributed/ucx-py)`

Not sure what this is supposed to mean. Do you just want to write `ucx-py (RAPIDS)` ?

Also not sure how you're specifying transitive dependencies, e.g. if you're optionally depending on cudf, do you also need to depend on rmm (which is a transitive dep of cudf)?

**Comment by jakirkham** [comment]
^ @pentschev, do you have thoughts on this question?

**Comment by pentschev** [comment]
> `(via distributed/ucx-py)`
> 
> Not sure what this is supposed to mean. Do you just want to write `ucx-py (RAPIDS)` ?

I just tried to be somewhat verbose, not even sure this is a necessity. What I meant to say is that the dependency is Dask-CUDA->Distributed->UCX-Py->UCX, and it is an important dependency for us, thus the verbosity. I'll defer to @jakirkham on how that can be best viewed.

> Also not sure how you're specifying transitive dependencies, e.g. if you're optionally depending on cudf, do you also need to depend on rmm (which is a transitive dep of cudf)?

Again just for verbosity. Users may have cuDF workflows that depend on RMM, or just CuPy (for example) workflows that also depend on RMM. With that said, I just wanted to make sure this is properly visualized, if this is only overhead I'm fine reorganizing or removing transitive dependencies altogether, probably @jakirkham has a best idea of what's important and could remove any overheads.

**Comment by jakirkham** [comment]
Yeah no strong feelings here. Understand what is written above. Ok with the other alternatives mentioned in the thread

**Comment by jakirkham** [comment]
In PR ( https://github.com/rapidsai/dask-cuda/pull/1130 ), we are trying to update to PyNVML 11.5.0, but are having some issues ( https://github.com/rapidsai/dask-cuda/pull/1130#issuecomment-1444539800 )

AIUI PyNVML 11.5.0 is compatible with CUDA 12. Checking to see if an older PyNVML version would suffice

**Comment by jakirkham** [comment]
After checking offline, have confirmed we need PyNVML 11.5.0+ for CUDA 12 support.
