### ISSUE TITLE
Is the use of `__main__` necessary for `LocalCUDACluster`?

### ISSUE THREAD

**Issue by trivialfis** [rapidsai/dask-cuda#1152]
Hi, I just read the new quickstart here: https://docs.rapids.ai/api/dask-cuda/stable/quickstart.html#localcudacluster thanks to https://github.com/dmlc/xgboost/pull/9008 .

My question is, in the Python script environment instead of a notebook, is wrapping code under:
``` python
if __name__ == "__main__":
    ...
```
necessary for CUDA cluster?

**Comment by trivialfis** [comment]
Thank you for confirming! Would you like me to open a PR for document to reflect this requirement?

**Comment by wence-** [comment]
Oh, yes please! Please target the 23.06 branch.
