### ISSUE TITLE
[BUG] Unit test failure in test_spill

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/dask-cuda#121]
There's an inconsistent unit test failure at `dask_cuda/tests/test_spill.py:341`.

See: https://gpuci.gpuopenanalytics.com/view/RAPIDS%20branch-gpu-matrix/job/gpuCI/job/dask-cuda/job/branches/job/dask-cuda-gpu-matrix-branch-0.9/CC_VERSION=5,CUDA=9.2,LINUX_VERSION=ubuntu16.04,PYTHON_VERSION=3.6/30/console

**Comment by pentschev** [comment]
@raydouglass thanks for the bug report. To the best of my testing, this was solved by #126, more specifically one commit that was not part of the merge, but required in order for tests to pass: https://github.com/rapidsai/dask-cuda/pull/126/commits/e76c51da0ac8cff6967f06459ca2f33e19b90e2c.

I'm thus closing this, but if this happens again, feel free to reopen.
