### ISSUE TITLE
Pooling memory (DRAM) from multiple GPUs

### ISSUE THREAD

**Issue by Dillon214** [rapidsai/dask-cuda#1216]
Hello dask-cuda devs,

Would it be possible to create a LocalCUDACluster with one worker, but with the pooled memory resources of multiple GPUs? I'm not sure how to accomplish this, being very new to the world of GPU-powered computing. 

-Dillon

**Comment by pentschev** [comment]
No, Dask-CUDA's design model is to create one worker per GPU, see https://docs.rapids.ai/api/dask-cuda/nightly/#motivation for details, as such you parallelize work among all the GPUs (i.e., workers) in a cluster and your cluster forms a pool of the memory of all GPUs combined.

**Comment by pentschev** [comment]
Maybe my phrasing above is dubious, so let me clarify: the cluster will have as much memory as all GPUs combined, but it won't form a pool in the sense of Worker A needs X bytes and Worker B has X bytes, so Worker A will use Worker's B memory to allocate. If you need more memory in a GPU than it has available, you'll either need to enable [device spilling](https://docs.rapids.ai/api/dask-cuda/nightly/spilling/) or resort to [using `rmm_managed_memory=True`](https://docs.rapids.ai/api/dask-cuda/nightly/api/#dask_cuda.LocalCUDACluster).

**Comment by Dillon214** [comment]
Hi Peter,

Enabling rmm_managed_memory worked like a charm! Thank you for the quick reply and quality advice, please consider this problem resolved. And, if you don't mind me asking, why do you say 'resort to' using rmm_managed_memory? Is there any big dowside to this, I noticed in the API that is would cause incompatibility with NVLink but so far that's it. Interested to know your thoughts. 

-Dillon

**Comment by pentschev** [comment]
> Is there any big dowside to this, I noticed in the API that is would cause incompatibility with NVLink but so far that's it. Interested to know your thoughts.

This is the primary downside, it actually now works starting with UCX 1.14.0 but on some preliminary benchmarks I did the performance was not great. So if you need ultimate performance, managed memory may not be the best choice. JIT-Unspill may perform considerably better than managed memory, but it may not be supported by all data types.

I'll close this issue now, but feel free to reopen if needed or open a new one if you have unrelated questions.
