### ISSUE TITLE
Tests failing after Distributed upstream changes

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#1224]
Changes in https://github.com/dask/distributed/pull/8083 have broken [all nightly tests](https://github.com/rapidsai/dask-cuda/actions/runs/5972198402/job/16202373197). If I didn't overlook anything, only `test_explicit_comms.py` and `test_spill.py` tests were broken.

@madsbk would you mind looking at the explicit comms tests? I have to still look in more details of what exactly changed w.r.t. spilling but I see the size of data that gets stored in `zict.Buffer` has changed, which indicates a change in how sizes are computed or that the stringify changes really changed the underlying stored data.

**Comment by quasiben** [comment]
@rjzamora if you have time can you also take a look here ?

**Comment by wence-** [comment]
Let me have a go...

**Comment by wence-** [comment]
Should be fixed by #1225.
