### ISSUE TITLE
ipywidgets missing

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#124]
When using dask-cuda with notebook for the first time there is a slight barrier.  dask-cuda uses `ipywidgets` but this is not a hard dependency.  Should it be ?

cc @shwina

**Comment by mrocklin** [comment]
No, I don't think so.  People will want to use dask-cuda non-interactively
without having the full ipython/Jupyter stack also installed.  Dask also
makes this same choice.
