### ISSUE TITLE
Dask-CUDA + NVLINK - IB

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#125]
This very well may be a question for `distributed` -- Is it possible to start the scheduler and workers on TCP but still direct distributed to use UCX (nvlink) when transporting GPU data between devices ?

cc @shwina @mrocklin

**Comment by madsbk** [comment]
@quasiben, running UCX with tcp and cuda_ipc should work. IB shouldn't be required.

**Comment by quasiben** [comment]
@madsbk, yes! Thank you.  I think I filed the issue when this was not the case.
