### ISSUE TITLE
Add option to use `cudf` spilling with `dask cuda`

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cuda#1280]
Currently if some one wants to enable `cudf-spilling` on a dask-cuda cluster they have to do below. 

```python3
def enable_spilling():
    import cudf
    cudf.set_option("spill", True)

cluster = LocalCUDACluster()
                    
enable_spilling()
client = Client(cluster)    
client.run(enable_spilling)
```

I dont think that is a great experience, especially given that this may not work cleanly with `jit_unspill` .  We should add a `cli` to do this to make this process easier. 

**Proposed Change:**
```python3
cluster = LocalCUDACluster(cudf_spill=True)
```

**Comment by quasiben** [comment]
We also want to enable [spill stats](https://docs.rapids.ai/api/cudf/stable/developer_guide/library_design/#statistics) as well.  JIT-unspill _should_ be disabled.  device-memory-limit could be enable but perhaps we should show a warning

**Comment by pentschev** [comment]
Addressing this via https://github.com/rapidsai/dask-cuda/pull/1362 .

I still need to explore further how to deregister cuDF spilling to prevent Dask and cuDF spilling dataframes concurrently and filed #1363 for that.

FYI @dantegd @madsbk @trivialfis
