### ISSUE TITLE
Dask-CUDA 23.12.0 requires `rapids-dask-dependency` on PyPI

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#1297]
Recently some changes were made to `dask-cuda` packages to depend on `rapids-dask-dependency` ( https://github.com/rapidsai/dask-cuda/pull/1270 ) to make managing the Dask dependency easier

The recently released `sdist` and `whl` on PyPI of `dask-cuda` for 23.12 require `rapids-dask-dependency`. However it looks like there is not a 23.12 release of `rapids-dask-dependency` yet. Raised upstream issue ( https://github.com/rapidsai/rapids-dask-dependency/issues/12 ) to follow-up

Am unsure whether to expect this at this stage (we are in the midst of the 23.12 release) or if there is some issue/bug that we need to dig into further

For now am filing this to track as well as let other users know this doesn't work yet (should they bump into it as well)

**Comment by vyasr** [comment]
The publishing of dask-cuda to PyPI was erroneous and won't be happening this way in the future. Up until this release dask-cuda was publishing both nightlies and final releases directly to PyPI on its own independently of the rest of RAPIDS. In the future, dask-cuda nightlies will be published to our nightly index instead, and we'll go through our internal processes for getting the final releases uploaded to PyPI. That matches what we'll be doing for rapids-dask-dependency, so the timelines will be aligned.

**Comment by jakirkham** [comment]
Am able to `pip install dask-cuda` now that `rapids-dask-dependency`

Closing as resolved

That said, we should keep an eye out for similar issues in 24.02 as the release process is ironed out (still a few moving parts as noted above)
