### ISSUE TITLE
pip install dask-cuda install dask-cuda 0.6.0

### ISSUE THREAD

**Issue by lesteve** [rapidsai/dask-cuda#130]
`pip install dask-cuda` installs dask-cuda 0.6.0. I got this when first trying to install dask-cuda (I use pip for dask-jobqueue so I tried pip first for dask-cuda is probably the main reason I got this). I then got confusing errors about scheduler_port or something like this.

I guess just removing the 0.6.0 package may be enough, otherwise uploading a dummy package with setup.py raising an error saying that you need to install from the rapidsai conda channel.

**Comment by pentschev** [comment]
@mike-wendt @raydouglass @rlratzel @dillon-cullinan do you think this is something we could do? It can be confusing for people who will look for RAPIDS packages in pip, so maybe we could remove or raise an error for all RAPIDS pip packages?

**Comment by lesteve** [comment]
Just a comment before I forget, what you probably do *not* want do do is to completely remove the project from PyPI. This would allow anyone to squat the project name and upload anything they want there.

See https://twitter.com/VictorStinner/status/1156150349385875456 for a case when this happened recently.

**Comment by mrocklin** [comment]
I think that we should publish dask-cuda on PyPI.  It's generally useful
and not just for RAPIDS.

**Comment by pentschev** [comment]
@lesteve thanks for the hint, I really did not know that and we definitely must avoid it!

@mrocklin I'm ok with publishing this project on PyPI, but I guess we could still error out other RAPIDS packages.

**Comment by trivialfis** [comment]
Hi @mrocklin may I ask is there anything blocking this?

**Comment by mrocklin** [comment]
I don't know.  I actually don't manage publishing RAPIDS packages.  For that you will have to talk to the RAPIDS ops team: @mike-wendt @raydouglass @rlratzel @dillon-cullinan

**Comment by trivialfis** [comment]
Hi @mike-wendt @raydouglass @rlratzel @dillon-cullinan I'm currently supporting the XGBoost's dask interface, which recommends using dask-cuda for scaling up to GPU clusters.  By default XGBoost uses Pypi to distribute the Python package, can we consider support Pypi for dask-cuda?  I can allocate extra bandwidth for maintaining the package if that's needed.

**Comment by trivialfis** [comment]
@mrocklin Thanks for the references.

**Comment by kkraus14** [comment]
> Hi @mike-wendt @raydouglass @rlratzel @dillon-cullinan I'm currently supporting the XGBoost's dask interface, which recommends using dask-cuda for scaling up to GPU clusters. By default XGBoost uses Pypi to distribute the Python package, can we consider support Pypi for dask-cuda? I can allocate extra bandwidth for maintaining the package if that's needed.

In general we don't publish PyPI packages because the requirements for manylinux compliant wheels is nearly impossible to deal with for native code that uses CUDA. You can read about why we decided to drop PyPI packages here: https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472

**Comment by mrocklin** [comment]
@kkraus14 the dask-cuda package is pure Python, and not particularly tied in any way to the other RAPIDS codebases.  It is used by other non-RAPIDS packages that do publish PyPI packages, like XGBoost.

**Comment by JohnZed** [comment]
Yes, I'm onboard with reasoning behind conda elsewhere, but dask-cuda is a super-lightweight python-only package. Would be great to get PyPI support. This will really help XGBoost but also other Dask users still on pip to support GPUs.

**Comment by raydouglass** [comment]
After some internal discussion, we plan to reintroduce pip support for dask-cuda. Working prioritizing this so I can provide a time estimate.

**Comment by trivialfis** [comment]
Awesome!

**Comment by pentschev** [comment]
This has been recently solved, we now have [nightly builds](https://pypi.org/project/dask-cuda/#history), and the next release should come out in a few weeks.
