### ISSUE TITLE
Broken link in explicit_comms docs

### ISSUE THREAD

**Issue by yoldemir** [rapidsai/dask-cuda#1328]
Hi there!

The API link on this page appears broken: https://docs.rapids.ai/api/dask-cuda/nightly/explicit_comms/

This is the specific link that's not working: https://docs.rapids.ai/api/dask-cuda/nightly/explicit_comms/api.html

**Comment by pentschev** [comment]
Fixing in https://github.com/rapidsai/dask-cuda/pull/1329 .
