### ISSUE TITLE
Pin newer pandas version

### ISSUE THREAD

**Issue by secrettoad** [rapidsai/dask-cuda#1336]
Hi dask team. My team and I use dask-cuda for distributed training of deep learning models, and are just now putting together our first xgboost model on dask. However, the dask implementation of the model available in the main xgboost package uses pandas 2.2.2 and, for that reason, we run into serialization errors when following the docs.

My question is, can we please pin 2.2.2 or at least a >2 pandas version within the package? I am not an expert on dask-cuda, but do not myself see why a particular pandas version is required.

Any insight you can share is much appreciated. Thank you

`dask-cuda 24.2.0 depends on pandas<1.6.0.dev0 and >=1.3`

**Comment by vyasr** [comment]
This is resolved in dask-cuda 24.4! See #1306. Feel free to post again if you have any more questions.

**Comment by secrettoad** [comment]
oh excellent. thank you so much
