### ISSUE TITLE
Automatically determine topology for dask-cuda-worker

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cuda#135]
Currently dask-cuda-worker does a very small amount of automatic detection in order to build out a set of Dask workers for the local machine.

1.  Find out how many GPUs there are and how much total host memory, and launch one worker per GPU

In dgx.py we learned that there was a lot more configuration to do if we have more information:

1.  Network interfaces
2.  CPU affinity
3.  device memory

This information was hard coded.  As we deal with machines that are not DGX-1's it would be nice to automatically find this information. 

@pentschev suggested that we might be able to get this from PyNVML and I think he's looking at it now.  cc'ing @rjzamora , just as an FYI, though I'm not sure there is much for you to do at the moment.

**Comment by pentschev** [comment]
Item 2 was addressed by #138 and item 3 was already addressed and further improved in #140 , but item 1 still requires further investigation.

**Comment by pentschev** [comment]
Item 1 has been also addressed in https://github.com/rapidsai/dask-cuda/pull/205, closing.
