### ISSUE TITLE
[BUG] Conda vs Pypi dask dependency issue

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/dask-cuda#16]
Since the conda dependency is `dask-core`, but the pypi one is `dask`, this prevents the conda build from working.

The conda build delegates to `setup.py` and this process will attempt to download `dask`. conda-build errors on any setuptools downloads.

**Comment by jakirkham** [comment]
So what we typically did in conda-forge when building a Python package is run the following, which stops `setuptools` from pulling in dependencies. These days conda-forge builds with `pip`, but I don't think we should get into that yet.

```
python setup.py install --single-version-externally-managed --record=record.txt
```

Where is `setup.py` being called currently? Would it be easy to add these flags there? If not, there are other options. Just trying to get a sense of what it would take to correct this near term.

**Comment by raydouglass** [comment]
> Where is `setup.py` being called currently? Would it be easy to add these flags there? If not, there are other options. Just trying to get a sense of what it would take to correct this near term.

https://github.com/rapidsai/dask-cuda/tree/branch-0.6/conda/recipes/dask-cuda

**Comment by jakirkham** [comment]
Alright have submitted PR ( https://github.com/rapidsai/dask-cuda/pull/17 ) to fix this. Please take a look when you have a chance :)

**Comment by jakirkham** [comment]
Please let me know if that fixes it or if there are still issues that need attention.
