### ISSUE TITLE
Drop call to ucp.reset

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#164]
Currently it appears dask-cuda [calls `ucp.reset` before calling `ucp.init`]( https://github.com/rapidsai/dask-cuda/blob/ac37fedbb01b81d99b3afe0038b5981b9f115ce7/dask_cuda/initialize.py#L73-L74 ). However it would be preferable to avoid the call to `ucp.reset` in favor of initializing `ucp` once.

cc @madsbk @quasiben

**Comment by jakirkham** [comment]
@mrocklin, are you aware of `ucp.init()` being called at an earlier stage like in `distributed`?

**Comment by mrocklin** [comment]
It looks like we never call `ucp.init` in the `distributed` codebase

```bash
(dev) MROCKLIN-MLT:distributed mrocklin$ git grep ucp.init
(dev) MROCKLIN-MLT:distributed mrocklin$
```

**Comment by mrocklin** [comment]
Unfortunately I don't know much about the dask/ucx connection.  Most of the ucp code is in `distributed/comm/ucx.py` I think.

**Comment by jakirkham** [comment]
No worries. I think @pentschev or @madsbk probably have a better working knowledge of what is going on here.

**Comment by pentschev** [comment]
`ucp.init` is implicitly called, but we can definitely call it directly to ensure specific options are passed. Regardless, I think @madsbk is going to work on a clean way of initializing ucx-py from distributed next week, which is going to solve this issue and we won't need to call `ucp.reset` here anymore.

**Comment by jakirkham** [comment]
Were you able to workaround this, Peter?

**Comment by pentschev** [comment]
No, we will need a clean solution. My idea is to allow passing parameters to the communication protocol, in our case UCX. These parameters which today are handled by the preload script in dask-cuda would then be passed to `distributed/comm/ucx.py` to do a proper initialization rather than re-initializing that later. Maybe @madsbk will come up with an even better solution next week.

**Comment by jakirkham** [comment]
Any updates here @madsbk and @pentschev? 🙂

**Comment by pentschev** [comment]
@madsbk is working on this in https://github.com/dask/distributed/pull/3178, but I think there's still quite some ground to cover.

**Comment by pentschev** [comment]
@jakirkham as a workaround for the time being, you can use https://github.com/dask/distributed/pull/3193 and comment out the `ucp.reset` call https://github.com/rapidsai/dask-cuda/blob/branch-0.11/dask_cuda/initialize.py#L73, this should unblock this while the proper solution is in the works by @madsbk.

**Comment by madsbk** [comment]
This should be fixed by https://github.com/rapidsai/dask-cuda/pull/168

**Comment by pentschev** [comment]
It is fixed indeed. Thanks @madsbk for working on it!
