### ISSUE TITLE
CUDA context not always initialized with dask-cuda-worker

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#176]
CUDA context seems not to get initialized when using a split setup (`dask-scheduler`, `dask-cuda-worker` and client code running in different processes).

https://github.com/dask/distributed/pull/3240 addresses the issue for CuPy, but custom CUDA libraries using the CUDA driver API will possibly fail due to the lack of the CUDA context.

The error manifests itself by showing output such as the following:

```
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

**Comment by jakirkham** [comment]
> [dask/distributed#3240](https://github.com/dask/distributed/pull/3240) addresses the issue for CuPy, but custom CUDA libraries using the CUDA driver API will possibly fail due to the lack of the CUDA context.

Have tried to extend this solution to any other CUDA objects with PR ( https://github.com/dask/distributed/pull/3666 ).

cc @madsbk

**Comment by pentschev** [comment]
I think this is not the case anymore, I haven't seen any of that nor there have been any reports recently. Tentatively closing, feel free to reopen should this show up again.
