### ISSUE TITLE
Support CUDA use in dask-ssh

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cuda#2]
The dask-ssh tool currently in https://github.com/dask/distributed/blob/master/distributed/deploy/ssh.py makes it easy to deploy Dask across a cluster of many machines with ssh.  It would be nice to find a way to extend this tool to handle the same sorts of considerations as we did in LocalCUDACluster.  

Note that we might also want to split off dask-ssh to a different repository and refactor it a bit.  See https://github.com/dask/distributed/issues/2497

**Comment by mt-jones** [comment]
Agree.

It would be nice if this solution used a scheduler _if available_, or Kubernetes, etc., _if available_; however, by default, the solution should use only SSH.

In the case of SSH, we'll need to specify some basic information about the user-defined cluster. My view is that it should be something like this:

```python
from dask_cuda import CUDACluster
from dask.distributed import Client

_cluster = [
  (10.11.121.314, "MASTER"),
  (10.11.121.315, "WORKER"),
  (10.11,121,316, "WORKER"),
  ...
]

cluster = CUDACluster(_cluster)
client = Client(cluster)
```

Note: IPs are for illustration! Above is a suggestion for an API.

**Comment by mrocklin** [comment]
I think that things like Kubernetes or other job schedulers are out of scope for this.  This is just using SSH.  Systems like Kubernetes will likely use the established dask-kubernetes (or other) package.

For SSH API I recommend looking at the docs for the existing dask-ssh implementation: https://docs.dask.org/en/latest/setup/ssh.html

Thoughts on changing that API are welcome (especially on the issue pointed to above) as there isn't currently a Python API for it.

**Comment by mrocklin** [comment]
After thinking about this now, my hope is that we can accomplish this entirely by using #3 and improving the mainline dask-ssh tooling

**Comment by mt-jones** [comment]
I think it would be good to provide the user the ability to orchestrate a multi-node cluster from a REPL or notebook environment; though, I'm not opposed to the API specified in the first link.

We should also be mindful that not every GPU on every node will be available for use.

**Comment by mt-jones** [comment]
To that end, we should let the user specify which IP also maintains the client/master.

**Comment by mrocklin** [comment]
Python API to dask-ssh and specifying scheduler IPs is probably not CUDA specific.  I'll move that conversation to the dask/distributed issue listed above and cc you there.
