### ISSUE TITLE
Incorrect conda pkg naming

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/dask-cuda#21]
https://anaconda.org/rapidsai-nightly/dask-cuda for conda pkgs uses `dask-cuda` and I'm pretty sure that a `-` in the pkg name is not to spec

this is why we have https://anaconda.org/rapidsai-nightly/dask_cudf

can we fix this for the release?

**Comment by jakirkham** [comment]
Having a `-` in conda package names generally is acceptable.

> It may contain "-", but no spaces.

Though there may be RAPIDS specific conventions that I'm unaware of. So feel free to link relevant docs so I can familiarize myself.

ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#package-section

**Comment by mrocklin** [comment]
Dask packages generally follow the `dask-foo` convention

**Comment by raydouglass** [comment]
Agreed. We're going to update all three dask-* to consistently use dashes.
