### ISSUE TITLE
New arguments in dask-cuda-worker 0.11

### ISSUE THREAD

**Issue by benjha** [rapidsai/dask-cuda#221]
Hi @mrocklin @pentschev 

I  am wandering how to use the dask-cuda-worker's new flags and like to know some other news in ver. 0.11 

In particular, 

1. Does UCX only work with TCP in ver 0.11? 

2. In  ver. 0.9 what I had to run the dask-cuda-workers was:
```
dask-cuda-worker --scheduler-file my-scheduler-gpu.json  --local-directory $mydir  --nthreads 1 --memory-limit 100GB --device-memory-limit 16GB  --death-timeout 60 --interface ib0
```
in ver 0.11, using ```--enable-infiniband```  and ```--enable-nvlink```  now I have:
```
dask-cuda-worker --scheduler-file my-scheduler-gpu.json  --local-directory $mydir  --nthreads 1 --memory-limit 100GB --device-memory-limit 16GB  --death-timeout 60 --interface ib0 --enable-infiniband --enable-nvlink
```
I got no errors in Summit, but want to know if  this is the correct use of    ```--enable-infiniband``` and ```--enable-nvlink```. 

3. What additional functionality is enabled by ```--enable-infiniband``` and ```--net-devices``` flags  that is not available when using  ```--interface``` ?

Thanks,

**Comment by pentschev** [comment]
> Hi @mrocklin @pentschev
> 
> I am wandering how to use the dask-cuda-worker's new flags and like to know some other news in ver. 0.11

Hi @benjha , there hasn't been many changes in 0.11 besides some UCX support and the introduction of a few benchmarks for UCX as well. We have also simplified the `LocalCUDACluster` which now includes everything it had before, plus UCX support, and as a consequence of that, we deprecated the `DGX` class.

> In particular,
> 
> 1. Does UCX only work with TCP in ver 0.11?

Yes, it does. We still don't see much benefit of using it yet, in fact using UCX without NVLink or InfiniBand is generally slightly slower up to the extent we have tested it. We're still investigating why TCP over UCX (i.e., when NVLink and InfiniBand are unavailable/disabled) doesn't perform better than Python sockets.

> 2. In  ver. 0.9 what I had to run the dask-cuda-workers was:
> 
> ```
> dask-cuda-worker --scheduler-file my-scheduler-gpu.json  --local-directory $mydir  --nthreads 1 --memory-limit 100GB --device-memory-limit 16GB  --death-timeout 60 --interface ib0
> ```
> 
> in ver 0.11, using `--enable-infiniband` and `--enable-nvlink` now I have:
> 
> ```
> dask-cuda-worker --scheduler-file my-scheduler-gpu.json  --local-directory $mydir  --nthreads 1 --memory-limit 100GB --device-memory-limit 16GB  --death-timeout 60 --interface ib0 --enable-infiniband --enable-nvlink
> ```
> 
> I got no errors in Summit, but want to know if this is the correct use of `--enable-infiniband` and `--enable-nvlink`.

This is the correct use of those flags.

> 1. What additional functionality is enabled by `--enable-infiniband` and `--net-devices` flags  that is not available when using  `--interface` ?

The `--interface` option is only used to establish the Dask connection and it's necessary to use an Ethernet interface strictly (not and InfiniBand one), whereas the `--net-devices` is only used to define what InfiniBand interface should be used by each individual worker. I just realized the documentation for both of these options hasn't been properly updated in 0.11, which was my mistake and I'll fix it upstream. The `LocalCUDACluster` class documents those correctly, and that can be found in https://github.com/rapidsai/dask-cuda/blob/branch-0.12/dask_cuda/local_cuda_cluster.py#L86-L89 and https://github.com/rapidsai/dask-cuda/blob/branch-0.12/dask_cuda/local_cuda_cluster.py#L106-L118.

**Comment by jakirkham** [comment]
Any other questions here @benjha?

**Comment by benjha** [comment]
@jakirkham  I don't have any other question. 
Thanks!

**Comment by pentschev** [comment]
Thanks @benjha , I'm closing it then.
