### ISSUE TITLE
Allow initialization of RMM upon creation of workers

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#233]
To ensure a smoother operation, both from the user's perspective and internal Dask multithreading, we should make sure we can initialize RMM upon the creation of each worker.

cc @jakirkham @quasiben @kkraus14

**Comment by jakirkham** [comment]
For context, today people are doing this.

```python
rmm.reinitialize(
    pool_allocator=True,
    managed_memory=False,
    initial_pool_size=2**31,
)
client.run(
    rmm.reinitialize,
    pool_allocator=True,
    managed_memory=False,
    initial_pool_size=2**31,
)
```

**Comment by beckernick** [comment]
cc @ayushdg as we were discussing this

**Comment by jakirkham** [comment]
Should add `rmm.reinitialize` takes a `device` argument. Guessing we will want to align that with how devices are distributed per worker.

**Comment by pentschev** [comment]
The [`CUDA_VISIBLE_DEVICES` variable is rotated for each worker process](https://github.com/rapidsai/dask-cuda/blob/branch-0.13/dask_cuda/local_cuda_cluster.py#L43), what that means is that the GPU assigned to the process is always `0`.

**Comment by jakirkham** [comment]
Ah ok. So the default value for `devices` is already fine.
