### ISSUE TITLE
Batching data + using custom functions

### ISSUE THREAD

**Issue by sadatnfs** [rapidsai/dask-cuda#238]
Hey everyone,

I'm a super new user to the Dask and CUDA/cuDF/GPU framework, and am very excited to be using this given the promising speedups! I had a couple of questions (if this is not the right place, please feel free to point me to a forum or somewhere else I can ask around!):

1) My Azure VM has 4 P100 GPUs, each with 16gb of memory. The dataset I have is about 15gb on memory, and so if I load it with the usual cuDF API, then it loads it all into a single GPU, and trying to do any ops on it spawns OOM issues. That's why I decided to give Dask-CUDA a try, and lo and behold, using a local CUDA cluster splits the data into 4 GPUs (when I call persist())!

Here's one issue: I might have a use case where I'll need way larger memory to work with. Is there any existing methods available where I can work with batches of data instead of having it all running at the same time?

2) I've seen in a bunch of documentation that the amazing `apply_rows()` function is not yet available in Dask-CUDA. There are a bunch of custom functions I need to use in order to do a bunch of custom analysis on my data, which might not necessarily work with `applymap`. Do you guys have any tips on popular workarounds for using custom functions with Dask CUDA frames?

Thanks so much!

**Comment by mrocklin** [comment]
Hi Nafis,

This doc page might have some pointers for you:
https://docs.dask.org/en/latest/best-practices.html#learn-techniques-for-customization

**Comment by sadatnfs** [comment]
Thanks @mrocklin! It looks like the base Dask does allow for something like a custom aggregation for each group of choice. 
That is sort of what I'd like to do: for each group, I want to do some math and then run a linear regression. AFAIK dask-cudf doesn't allow for that yet eh?

**Comment by sadatnfs** [comment]
To be precise, it looks like custom aggregations can be done in the regular case with `dask.dataframe.Aggregation`

**Comment by pentschev** [comment]
> I've seen in a bunch of documentation that the amazing apply_rows() function is not yet available in Dask-CUDA.

Only a small clarification, dask-cuda isn't adding any specific support for Dask, Arrays or DataFrames, it's just a helper to mainline dask/distributed, simplifying CUDA availability. That said, if some specific function on a Dask Array or Dask DataFrame isn't available, that could be because Dask itself doesn't implement it, or some of the CUDA libraries, such as cuDF.

> That is sort of what I'd like to do: for each group, I want to do some math and then run a linear regression. AFAIK dask-cudf doesn't allow for that yet eh?

dask-cudf is also a library implementing Pandas API, and just like Pandas doesn't implement linear regression, dask-cudf will not as well. I think what you're looking for is [cuML](https://github.com/rapidsai/cuml) (implements scikit-learn's API), which provides [Linear Regression](https://rapidsai.github.io/projects/cuml/en/latest/api.html#linear-regression) functionality, and can also operate on cuDF DataFrames.

**Comment by sadatnfs** [comment]
Thanks @pentschev ! Yeah I definitely plan to leverage cuML for the regressions, but there's a bunch of iterative math I'd like to do which will require me to write some custom functions. That's where I'd want to use something like `apply_rows()`

**Comment by pentschev** [comment]
AFAIK, there's `apply_rows`, there's a blogpost about it in cuDF (no Dask involved) [here](https://medium.com/rapids-ai/user-defined-functions-in-rapids-cudf-2d7c3fc2728d), and as far as I can see, [dask-cudf should also support `apply_rows`](https://github.com/rapidsai/cudf/blob/branch-0.13/python/dask_cudf/dask_cudf/core.py#L130). Do these work for you? I can't comment on whether it's fully supported, but if there's still missing pieces for you, I would strongly suggest opening an issue in [cuDF](https://github.com/rapidsai/cudf).

**Comment by jakirkham** [comment]
Any other questions @sadatnfs?

**Comment by sadatnfs** [comment]
@jakirkham oops I missed the last reply, apologies. Closing now!

**Comment by jakirkham** [comment]
No worries. Please let us know if other things come up 🙂
