### ISSUE TITLE
Consolidating DtoH and HtoD operations during spilling

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#250]
This was a suggestion that @jrhemstad made when we discussed this offline. Filing here for better tracking and visibility. Please feel free to add or correct anything Jake 🙂

In thinking about how we might improve the performance of spilling, one thought might be to pack all the buffers we plan to transfer to host or device into one single buffer. Then we perform the transfer of that single buffer to host or device as need.

Some thoughts to keep in mind with this idea. Normally we are spilling because we are low on memory. So we might need to consider carefully whether an additional allocation is a good idea here. Being able to avoid an allocation like by recognizing a single allocation is backing the whole object being spilled, would be very helpful.

While it's possible this is a faster way to transfer, it's possible this ends up being slower in some cases (especially if an additional copy is needed). So some heuristics may be needed to determine whether to move everything into a single allocation or not. This might be moot if we can recognize a single allocation is used for the whole object being spilled and just leverage that single allocation for spilling directly.

**Comment by jrhemstad** [comment]
> Normally we are spilling because we are low on memory. So we might need to consider carefully whether an additional allocation is a good idea here.

This is my biggest concern about this idea.

Have we tried spilling to pinned memory and doing the multiple D2H copies on separate streams?

**Comment by jakirkham** [comment]
Just allocating pinned memory alone or pinning existing memory was quite slow. Having a pinned memory pool might help though.

We haven’t explored separate streams.

**Comment by jakirkham** [comment]
We recently switched to `"dask"` serialization for spilling with PR ( https://github.com/rapidsai/dask-cuda/pull/256 ), which means it's now on the implementer of `"dask"` serialization to perform the DtoH and HtoD operations.

In the case of cuDF, that would be cuDF ( https://github.com/rapidsai/cudf/issues/3793 ). In the case of Numba or CuPy, that would be Distributed ( possibly with help from those libraries and/or RMM https://github.com/rapidsai/rmm/issues/318 ).

Going to close this out. Happy to discuss further in those issues.
