### ISSUE TITLE
Using `--net-devices="auto"` implicitly enables InfiniBand

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#255]
In some systems like DGX-1/DGX-2, `--net-devices="auto"` and `ucx_net_devices="auto"` will define `UCX_NET_DEVICES` to the topologically closest device, which is an InfiniBand device. This will implicitly enable InfiniBand and that's an undesirable behavior.

I don't have a clear one-size-fits-all solution now, but a potential one is to only allow `--net-devices="auto"`/`ucx_net_devices="auto"` if InfiniBand is explicitly enabled. The downside of such an approach is that it will limit a fair usage of automatic detection of closest devices if those are not IB devices (e.g., if the system has multiple Ethernet cards rather than IB interfaces).

cc @randerzander @quasiben for visibility

**Comment by jakirkham** [comment]
Would it be possible to get a short list of topologically close devices? If so, maybe we could use the next closest device on that list (if the closest is IB).

Alternatively could the topological distance code be adjusted to filter out IB?

**Comment by pentschev** [comment]
> Would it be possible to get a short list of topologically close devices? If so, maybe we could use the next closest device on that list (if the closest is IB).

Yes, but this can be dangerous today as we have no way to identify which of these devices are indeed connected. Many machines will have multiple Ethernet devices with only one connected and we have no guarantees we'll select the right one in this context, so users should specify the right device in that case, e.g., `--net-devices="eth0"`.

> Alternatively could the topological distance code be adjusted to filter out IB?

Also yes, but we currently don't support that either for the same reason mentioned above.

**Comment by pentschev** [comment]
For now, we're going with the solution of raising an exception should `ucx_net_devices="auto"` be specified and IB being disabled: https://github.com/rapidsai/dask-cuda/pull/291 , closing this.
