### ISSUE TITLE
Old exceptions pop-up if `dask-worker-space` persists

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#265]
Have noticed recently when running the dask-cuda tests that if `dask-worker-space` is still around, old tracebacks will pop-up from previous runs when tests fail. This may be a broader issue (belonging in dask or distributed). Just mentioning it here for now based on where I've been able to reproduce it.

**Comment by quasiben** [comment]
This is come up a number of times for @randerzander and @pentschev  as well

**Comment by pentschev** [comment]
Yes, on a related note, I saw it just this morning. I think the issue occurs more frequently when using UCX that `dask-worker`s/`dask-cuda-worker`s do not close correctly (see https://github.com/dask/distributed/issues/3576), thus leaving junk files behind.

**Comment by jakirkham** [comment]
Thanks for the context. Glad to know that it's not just me seeing this issue 😅

**Comment by jakirkham** [comment]
Prodding to keep open. The issue still exists. Though I don't think we know of a resolution currently

**Comment by pentschev** [comment]
I haven't seen or heard of this happening in quite a long time, I imagine either us or Distributed changed something that happened to fix the issue. I'll tentatively close this, but please reopen if you've experienced this recently.
