### ISSUE TITLE
Starting the cluster with memory_limit=None causes failures on the latest nightly

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cuda#271]
Starting the cluster with memory_limit=None causes failures on the latest nightly

#### Minimal Repro:
```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait
import dask 
 
def test_func():
    return "abc"
        

if __name__ == "__main__":
    cluster = LocalCUDACluster(memory_limit=None)
    client = Client(cluster)
    
    test_val = client.submit(test_func)
    print(test_val.result())
```
#### Trace:

```python
Traceback (most recent call last):
  File "test_bug.py", line 14, in <module>
    print(test_val.result())
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_march_30/lib/python3.7/site-packages/distributed/client.py", line 220, in result
    raise exc.with_traceback(tb)
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_march_30/lib/python3.7/site-packages/dask_cuda/device_host_file.py", line 139, in __setitem__
    self.host_buffer[key] = value
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_march_30/lib/python3.7/site-packages/zict/buffer.py", line 84, in __setitem__
    if self.weight(key, value) <= self.n:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

### Env:
```
dask-cuda                 0.14.0a200330           py37_35    rapidsai-nightly
```
### Work around:
Setting it to `auto` works.  
```
    cluster = LocalCUDACluster(memory_limit='auto')
```
### Other details: 

This used to work earlier 

```
dask-cuda                 0.13.0b200329           py37_86    rapidsai-nightly
```

CC: @ayushdg , who triaged  this.

**Comment by VibhuJawa** [comment]
Related Pr in all probab: https://github.com/rapidsai/dask-cuda/pull/269

**Comment by ayushdg** [comment]
Ah I think I see the change [here](https://github.com/rapidsai/dask-cuda/pull/269/files#diff-adfdb0f8dc34800895529621f06b1340L147).

Note: If we switch to `"auto"` the behavior with older nightlies will not work.

**Comment by jakirkham** [comment]
Why doesn't `"auto"` work on the older nightlies?

**Comment by ayushdg** [comment]
Because the logic for parsing memory from the string was added in this [pr](https://github.com/rapidsai/dask-cuda/pull/269/files#diff-adfdb0f8dc34800895529621f06b1340R148). If we go with `"auto"` on an older nightly, it fails with the following:
`TypeError: '<=' not supported between instances of 'int' and 'str'` similar to the stack trace posted above.

**Comment by jakirkham** [comment]
What is the expected behavior of `None` compared to `0` and `"auto"`?

**Comment by pentschev** [comment]
Is there a reason to write `memory_limit=None` for `LocalCUDACluster`? Note that this used to be the default in `LocalCUDACluster`, and was now changed to `"auto"` to match distributed, even though there's no change in behavior for those using the default value.

I would simply suggest removing this argument, which would work with both old and new versions of dask-cuda.

**Comment by ayushdg** [comment]
Thanks for the suggestion @pentschev.
Another thing I wanted to mention (probably should raise a new issue about this) is that `memory_limit="auto"` assigns a host memory limit per worker which can be significantly lower than the theoretical value it could take(assuming num cpu_cores > num_gpus). Relevant code [here](https://github.com/dask/distributed/blob/master/distributed/worker.py#L3158-L3159). There is an assumption here that `n_workers * n_threads = n_cores` which is true for the cpu cluster case but not necessarily true for a dask-cuda cluster.

**Comment by jakirkham** [comment]
Just to be clear `memory_limit` refers to host memory. There is a separate `device_memory_limit` for device memory, which we have discussed extending the same functionality too ( https://github.com/rapidsai/dask-cuda/issues/270 ).

**Comment by ayushdg** [comment]
> Just to be clear `memory_limit` refers to host memory. There is a separate `device_memory_limit` for device memory, which we have discussed extending the same functionality too ( #270 ).

Thanks for the clarification. Agreed that a discussion for #270 around device_limits would also be useful. 
To clarify my discussion w.r.t. `auto`, I am referring to defaults (auto) with host memory.

**Comment by pentschev** [comment]
@ayushdg the assumption you mentioned is correct for distributed, but it's slightly different for dask-cuda. `n_workers` is the number of GPUs https://github.com/rapidsai/dask-cuda/blob/branch-0.14/dask_cuda/local_cuda_cluster.py#L147, and `n_threads` is `1` https://github.com/rapidsai/dask-cuda/blob/branch-0.14/dask_cuda/local_cuda_cluster.py#L126.

**Comment by ayushdg** [comment]
> @ayushdg the assumption you mentioned is correct for distributed, but it's slightly different for dask-cuda. `n_workers` is the number of GPUs https://github.com/rapidsai/dask-cuda/blob/branch-0.14/dask_cuda/local_cuda_cluster.py#L147, and `n_threads` is `1` https://github.com/rapidsai/dask-cuda/blob/branch-0.14/dask_cuda/local_cuda_cluster.py#L126.

This is exactly what I wanted to discuss. Assuming a case where I have a system with 64 cores, 4 GPUs and 64GB ram. When starting a `LocalCUDACluster` each worker should theoretically be assigned `16 GB` host memory. Instead based on the current codepath each worker would only be assigned `1 GB` host memory, due to the `System_Memory * min(1,num_threads / num_cores)` logic in distributed.

**Comment by pentschev** [comment]
That codepath is overridden by https://www.ft.com/content/b6ca9ded-00d5-4eed-a9b7-ed76a5df818a, in other words, we precalculate how much memory each worker should use and pass an integer to distributed rather than `"auto"`.

**Comment by mrocklin** [comment]
I think that that is the first time that the Financial Times has been cited
in a Dask issue :)

**Comment by pentschev** [comment]
Nevermind, that codepath is _not_ overridden. It does take the minimum of 1 and `nthreads / nworkers`, which would be `min(1, 0.25)` for the case you mentioned, and then allow 25% of the system memory per worker (aka, GPU).

**Comment by ayushdg** [comment]
> Nevermind, that codepath is _not_ overridden. It does take the minimum of 1 and `nthreads / nworkers`, which would be `min(1, 0.25)` for the case you mentioned, and then allow 25% of the system memory per worker (aka, GPU).

Thanks for the clarification. You are right about the memory and we assign the correct values as expected. I was seeing this behavior with `dask-cuda-worker` and assumed the same would be happening with `LocalCUDACluster` as well.

**Comment by pentschev** [comment]
> I think that that is the first time that the Financial Times has been cited in a Dask issue :)

Hahaha! That teaches me not to respond from my phone at 2am anymore.

**Comment by pentschev** [comment]
> Thanks for the clarification. You are right about the memory and we assign the correct values as expected.

Glad it's clear now!

> I was seeing this behavior with dask-cuda-worker and assumed the same would be happening with LocalCUDACluster as well.

You were seeing this with dask-cuda-worker, or are you still seeing it? If you're still seeing that, there may still be a bug.
