### ISSUE TITLE
[DOC] Dask benchmark notebooks

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cuda#273]
@jakirkham @quasiben and I spent a bit of time a couple days ago putting together some benchmarking notebooksh for Dask workloads here: https://github.com/mrocklin/dask-gpu-benchmarks

Not sure if these are appropriate for this repository, but I thought that I'd mention them.

**Comment by pentschev** [comment]
I'm not sure what's the appropriate place for this. Perhaps at some point people would like to make them proper benchmarks rather than notebooks, as the ones that exist in https://github.com/rapidsai/dask-cuda/tree/branch-0.14/dask_cuda/benchmarks today.

**Comment by jakirkham** [comment]
@rlratzel or @kevingerman, are either of you working on benchmarking work these days? If so, where would be a logical place to add more benchmarks?

**Comment by pentschev** [comment]
I'm not sure whether this is still relevant, but notice we have some benchmarks in https://github.com/rapidsai/dask-cuda/tree/branch-0.17/dask_cuda/benchmarks, they're not notebooks though.
