### ISSUE TITLE
Workaround for dask default worker-space directory

### ISSUE THREAD

**Issue by samcmill** [rapidsai/dask-cuda#276]
When the E2E notebook is run from a read-only filesystem (e.g., a Singularity container image), dask does not start because it cannot write its `dask-worker-space` directory to the (read-only) current working directory.

The workaround is to modify the `LocalCUDACluster` call in cell 3 to add the `local_dir` parameter:

```
cluster = LocalCUDACluster(ip=IPADDR, local_dir='/tmp/dask_cuda')
```

Until this is fixed upstream, the workaround should be added to the notebook.

See https://github.com/dask/distributed/issues/2496.

**Comment by pentschev** [comment]
@dillon-cullinan there is nothing to be done for this in dask or dask-cuda. This is a default configuration that has to be changed based on the use case. Please move it back to rapidsai/notebooks or to a more appropriate location given this seems to be an issue with Singularity containers only.

**Comment by jakirkham** [comment]
IIUC that repo is slowly being eliminated and notebooks are being upstreamed to relevant repos. The issue tracker is already closed. So I think Dillon was just moving this here so it could still be tracked somewhere.

AIUI here are our options:

1. Close it (if there is nothing for us to do here)
2. Move it (if this is an upstream or other issue)
3. Document expected usage (if there is something users should do)
4. Fix it (if there is actually some kind of bug to fix)
5. Something else?

From what you have said, it sounds like 4 is out. Making a note in the README might be useful if we want to do 3. There is already an upstream issue so 2 is done (have also responded there recently). 1 is also an option given this is just as much an upstream issue as one here. Any other thoughts on what we should do here? 🙂

**Comment by jakirkham** [comment]
Inline with the decision in issue ( https://github.com/dask/distributed/issues/2496 ), I'm going to ahead and close it (option 1). There is some documentation work already planned in upstream issue ( https://github.com/dask/dask/issues/4286 ), which this option will be included in.

**Comment by pentschev** [comment]
Sorry @jakirkham , I had missed your previous comment, but I agree with closing this. Thanks!
