### ISSUE TITLE
[BUG] Deprecation warning at E2E.ipynb

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/dask-cuda#277]
**Describe the bug**
Hi,

When running the E2.ipynb mortages demo, the following warning is displayed:
![image](https://user-images.githubusercontent.com/26169771/57012498-22725580-6c07-11e9-8526-063f2352db20.png)

**Steps/Code to reproduce bug**
Run the first two cells.

**Expected behavior**
No warning is displayed.

**Environment details (please complete the following information):**
DGX-1 

**Additional context**

**Comment by pentschev** [comment]
This has been fixed quite some time ago in Dask upstream, closing.
