### ISSUE TITLE
[FEA] Dynamic configuration of worker device memory limits

### ISSUE THREAD

**Issue by beckernick** [rapidsai/dask-cuda#280]
I'd like to be able to dynamically configure worker device memory limits. Given a running cluster, a user may have various sized workloads. Some workloads would benefit from device memory limits, while others would be harmed by this. Requiring an explicit cluster bringdown/bringup to change memory limits can sometimes pose a real challenge. Allowing a user to dynamically configure a device memory limit would let them optimally run each individual workload.

From discussions with @pentschev , this would likely require changing the LRU parameters and require that the cache be empty. Given that, I wonder if this would be possible in something like a call to `Client.restart`, though of course not requiring that might be desirable, too.

**Comment by beckernick** [comment]
cc @randerzander

**Comment by pentschev** [comment]
Thanks for filing this issue @beckernick . Just to be sure, you wouldn't change any parameters regarding RMM during that process (e.g., pool size and default/managed memory), would you?

**Comment by pentschev** [comment]
@beckernick I think I mentioned before but changing the size of RMM pool at runtime isn't supported by UCX today, so you'll definitely be limited by it for the foreseeable future, but the spilling behavior is decoupled from UCX so that should be possible.

**Comment by beckernick** [comment]
Yes, thanks @pentschev . We're aligned on that 👍

**Comment by pentschev** [comment]
Is this and the proposed solution in https://github.com/rapidsai/dask-cuda/pull/281 still relevant @beckernick ?

**Comment by beckernick** [comment]
This is no longer relevant for the original motivating use case. I suspect that @madsbk 's work in #353 and his ongoing work to understand the details of the underlying device memory while spilling may further reduce the need for this.

With that said, it might be a nice small addition in the future.

**Comment by pentschev** [comment]
Thanks for confirming @beckernick . In the interest of keeping maintenance costs down to a minimum, I'll go ahead and close the PR and this issue. If in the future this becomes important again, we can pickup from where we left.
