### ISSUE TITLE
[DOC] dask-cuda-worker with --ucx-net-devices="auto" errors

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#283]
After installing the latest rapidsai 0.14 conda nightly packages, following the [ucx-py blog post](https://medium.com/rapids-ai/high-performance-python-communication-with-ucx-py-221ac9623a6a)'s dask-cuda-worker startup instructions:
```
dask-cuda-worker ucx://10.10.10.10:8786 --enable-tcp-over-ucx --enable-nvlink --enable-infiniband --ucx-net-devices="auto"
```
results in an error about the `ucx-net-devices` param:
```
Usage: dask-cuda-worker [OPTIONS] [SCHEDULER] [PRELOAD_ARGV]...
Error: no such option: --ucx-net-devices=auto
```

**Comment by quasiben** [comment]
currently, the option is `--net-devices` .  @pentschev should we change the option name in dask-cuda or update the blogpost ?

**Comment by pentschev** [comment]
Absolutely, but I think this isn't very pressing, so if people don't mind we would wait until we can stabilize UCX issues first. Any objections?

**Comment by randerzander** [comment]
Fixing the blog should be quick, no? People are referring to it as an example and getting hung up on the failure.

**Comment by pentschev** [comment]
Yes, I'm sorry, I thought we were talking about renaming to `--ucx-net-devices` in dask-cuda, which is something Ben and I discussed in the past. I have now fixed the blog, thanks @randerzander for bringing this up to our attention.

I'll leave this issue open as we intend to rename that to `--ucx-net-devices` in the future anyway.

**Comment by pentschev** [comment]
This is not relevant anymore since adding support for UCX >= 1.11.1, when we removed `--ucx-net-devices`. Closing.
