### ISSUE TITLE
LocalCudaCluster freezes when trying neural network prediction

### ISSUE THREAD

**Issue by anaszain89** [rapidsai/dask-cuda#311]
Hi,
I am new to dask and I was trying to run write a workflow to run inference on large images. I have attached the code Ive been using which should reproduce the issue I am facing.

Basically, if I use the distributed client scheduler with `(Processes=False)` and also when not using a scheduler, I am able to run inference of my data. 
However, when I try to use `LocalCudaCluster` as the scheduler, I run into issues. 

- In general, the process crashes and doesnt complete
- I have tried using with it 1 GPU/2 GPUs, using single threads and multiple threads per GPU. 
- It does seem to work for a subset of the data (and not will my full data)  (controlling dim0 in the `size` param in line 83), though much slower.

Quite possible, Im doing something incorrectly. The codes should help reproduce this. 

Thanks for your help figuring this out.

Anas
[Test_prediction.zip](https://github.com/rapidsai/dask-cuda/files/4747975/Test_prediction.zip)

**Comment by quasiben** [comment]
Thanks for the report @anaszain89 .  In general, I'd recommend getting a [Minimal Reproducible Example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) rather than something which requires downloading.  This makes maintenance and bug identification a lot easier


Dask-CUDA should only be executed with one thread and one worker per gpu:
https://dask-cuda.readthedocs.io/en/latest/specializations.html#automatic-instantiation-of-one-worker-per-gpu

Can I ask you to post the crash ?  Do you run out of memory ?  Etc.

**Comment by anaszain89** [comment]
Ah sorry about that! Here is the code that I had attached, its should reproduce the issue (slightly long just due to the actual network definition).

The `data_scale` parameter can control the overall size of the dask_array. That seems to be giving the issue. It works with `1` but not `16` for example.

There is not issue running it with `16` without specifying a scheduler or using a distributed client with `(Processes=False)`


```python

#
import cv2
import openslide
from dask import delayed
import numpy as np

import random

import dask
import dask.array as da
import dask_image.imread


from dask.distributed import Client
from dask_cuda import LocalCUDACluster

#
import torch
from torch import nn

# Defining a dummy `UNet`, predicts a two class output

def double_conv(in_channels, out_channels):
    return nn.Sequential(
        nn.Conv2d(in_channels, out_channels, 3, padding=1),
        nn.ReLU(inplace=True),
        nn.Conv2d(out_channels, out_channels, 3, padding=1),
        nn.ReLU(inplace=True)
    )   
class UNet2(nn.Module):
    def __init__(self, n_class):
        super().__init__()
        self.dconv_down1 = double_conv(3, 64)
        self.dconv_down2 = double_conv(64, 128)
        self.dconv_down3 = double_conv(128, 256)
        self.dconv_down4 = double_conv(256, 512)        
        self.maxpool = nn.MaxPool2d(2)
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)        
        self.dconv_up3 = double_conv(256 + 512, 256)
        self.dconv_up2 = double_conv(128 + 256, 128)
        self.dconv_up1 = double_conv(128 + 64, 64)
        self.conv_last = nn.Conv2d(64, n_class, 1)
    def forward(self, x):
        conv1 = self.dconv_down1(x)
        x = self.maxpool(conv1)
        conv2 = self.dconv_down2(x)
        x = self.maxpool(conv2)
        conv3 = self.dconv_down3(x)
        x = self.maxpool(conv3)   
        x = self.dconv_down4(x)
        x = self.upsample(x)        
        x = torch.cat([x, conv3], dim=1)
        x = self.dconv_up3(x)
        x = self.upsample(x)        
        x = torch.cat([x, conv2], dim=1)       
        x = self.dconv_up2(x)
        x = self.upsample(x)        
        x = torch.cat([x, conv1], dim=1)   
        x = self.dconv_up1(x)
        out = self.conv_last(x)
        return out

def get_predictions(model,da):
    with torch.no_grad():
        res = model(torch.FloatTensor(da).cuda())
    return res.cpu().numpy()


if __name__ == '__main__':

    
    # client = Client(processes=False)

    cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES='1')
    client = Client(cluster)
        
    model = UNet2(2)
    model.cuda()
    model.eval()
        
    bsz = 16
    data_scale = 16 # this parameter can control the size of the data it is okay with say using 1 but not with 16
    
    # generate a random image similar to my originial input 
    dimg = da.random.randint(0,255,size=(bsz*data_scale, 3, 2560, 2560), chunks=(bsz, 3, 256, 256), dtype='uint8')
    result = da.map_blocks(get_predictions,model,dimg,dtype=np.float32,chunks=(bsz,2,256,256))

    shape = result.compute().shape
    print('Shape of output : ', shape)

    client.shutdown()
```
I only see the following info with running with `data_scale=16`, perhaps there is a memory limit?

```python-traceback
/opt/conda/lib/python3.6/site-packages/distributed/node.py:244: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 43519 instead
  http_address["port"], self.http_server.port
distributed.worker - WARNING - Heartbeat to scheduler failed
Killed
```

**Comment by quasiben** [comment]
Thank you @anaszain89 .  When I ran your code I got a clearly identified memory error:

```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/datasets/bzaitlen/GitRepos/distributed/distributed/protocol/core.py", line 130, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/datasets/bzaitlen/GitRepos/distributed/distributed/protocol/serialize.py", line 302, in deserialize
    return loads(header, frames)
  File "/datasets/bzaitlen/GitRepos/distributed/distributed/protocol/serialize.py", line 64, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "/datasets/bzaitlen/GitRepos/distributed/distributed/protocol/pickle.py", line 66, in loads
    return pickle.loads(x)
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/storage.py", line 134, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/serialization.py", line 136, in _cuda_deserialize
    return storage_type(obj.size())
  File "/datasets/bzaitlen/miniconda3/envs/20200513/lib/python3.7/site-packages/torch/cuda/__init__.py", line 480, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 30.47 GiB already allocated; 7.44 MiB free; 30.49 GiB reserved in total by PyTorch)
distributed.core - ERROR - CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 30.47 GiB already allocated; 7.44 MiB free; 30.49 GiB reserved in total by PyTorch)
```

Note, I am running on 32GB V100 card

**Comment by anaszain89** [comment]
Thanks!
Oh I dont see that error. Perhaps due to an older version of the libraries? 
I had done a `pip install dask_cuda`
And I see the following:
```python
import dask_cuda
dask_cuda.__version__
`'0+unknown'`
```
Im currently using a 48GB Quadro 8000 (And max memory consumption during the process is around ~ 35 GB) 

Also, what I am trying to understand is why would a memory issue not happen without a scheduler or with a distributed Client ? Or maybe I am missing something here?

**Comment by quasiben** [comment]
Can you try installing from latest:

> python -m pip install git+https://github.com/rapidsai/dask-cuda.git


When I tried without LocalCUDACluster (no scheduler/client/worker) I also get a memory error

**Comment by anaszain89** [comment]
Oh yes, to reduce the overall memory for testing you could reduce the `bsz` parameter to 8
This brings down memory consumption to ~18 GB or so. 

I will test with the latest and circle back

**Comment by anaszain89** [comment]
Here is what I just got using `bsz=8` (total memory should be around ~18 GB)
It works without a scheduler
```python-traceback
Shape of output :  (128, 2, 2560, 2560)
```
With LocalCudaCluster
```python-traceback
Dask Cuda Version :  0.15.0a+5.g5dd1957
/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))
Killed
```

**Comment by quasiben** [comment]
With `bsz=8` I still get an out of memory error.  Did you also change `data_scale` ?

**Comment by anaszain89** [comment]
No I didnt change the scale (only `bsz=8`). I see ~18GB being used on the GPU

**Comment by jakirkham** [comment]
What kind of machine are you using for this @anaszain89?

**Comment by anaszain89** [comment]
This is a HP workstation with 48GB RTX8000 GPU

**Comment by quasiben** [comment]
@anaszain89 which cuda driver do you have if installed ?  RAPIDS is building support for CUDA 11 but this has not been released yet.  

LocalCUDACluster does not "require" any memory.  It does assume that the user will be spinning up one worker process per GPU though

**Comment by anaszain89** [comment]
I have CUDA 10.2 on my workstation and the other machine I tested with had CUDA 11.0 

I general I see that LocalCudaCluster (when it doesnt give an issue) takes up more memory on the GPU for this workflow

**Comment by jakirkham** [comment]
Dask-CUDA itself is not really using GPU memory. This is more likely a product of the workload being run and the behavior of other libraries (like CuPy or Pytorch). If you look at the Dask dashboard, you may find some clues as to what is happening.

**Comment by anaszain89** [comment]
Im actually comparing with and without using a scheduler (LocalCudaCluster).. 
In that case I think the overall memory consumption would be very similar. Unless there is some interactions with Pytorch that I am not understanding completely.

**Comment by quasiben** [comment]
There is no interaction between localcudacluster and PyTorch.  Are there any other updates her @anaszain89  ?

**Comment by quasiben** [comment]
Closing.  @anaszain89 if you are still running into issue feel free to reopen
