### ISSUE TITLE
`test_get_device_total_memory` fails

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#313]
The test currently fails due to changes in RMM, and only fails when another test involving RMM is executed prior to this. We have to check whether it's possible to really rollback the memory manager to Numba's default to make this pass, or find another way of checking GPU memory.

```python
======================================================== FAILURES ========================================================
______________________________________________ test_get_device_total_memory ______________________________________________

    def test_get_device_total_memory():
        # Ensure Numba is using its own memory manager, rather than RMM's
        cuda.set_memory_manager(cuda.cudadrv.driver.NumbaCUDAMemoryManager)

        for i in range(get_n_gpus()):
            with cuda.gpus[i]:
>               assert (
                    get_device_total_memory(i)
                    == cuda.current_context().get_memory_info()[1]
                )

dask_cuda/tests/test_utils.py:64:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../miniconda3/envs/rn-102-0.15.0b200608/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py:1023: in get_memory_info
    return self.memory_manager.get_memory_info()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <rmm.rmm.RMMNumbaManager object at 0x7fa4b52ed210>

    def get_memory_info(self):
>       raise NotImplementedError()
E       NotImplementedError

../../miniconda3/envs/rn-102-0.15.0b200608/lib/python3.7/site-packages/rmm/rmm.py:225: NotImplementedError
```

**Comment by jakirkham** [comment]
I don't think we can roll back to the Numba memory manager today. From [the docs]( http://numba.pydata.org/numba-doc/latest/cuda/external-memory.html#function ):

> The [`set_memory_manager()`]( http://numba.pydata.org/numba-doc/latest/cuda/external-memory.html#numba.cuda.set_memory_manager ) function can be used to set the memory manager at runtime. This must be called prior to the initialization of any contexts, and EMM Plugin instances are instantiated along with contexts.
>
> It is recommended that the memory manager is set once prior to using any CUDA functionality, and left unchanged for the remainder of execution.

We did discuss the possibility of changing the memory manager for specific contexts ( https://github.com/numba/numba/issues/5790 ). Though that is not implemented today.

cc @gmarkall (in case you have additional/other thoughts)

**Comment by pentschev** [comment]
Thanks @gmarkall , calling `cuda.close()` before setting the memory manager works! I've filed #315 to fix the test.

**Comment by gmarkall** [comment]
> Thanks @gmarkall , calling `cuda.close()` before setting the memory manager works! I've filed #315 to fix the test.

Thanks for confirming - I've added some additonal notes clarifying the use of `cuda.close()` and re-setting the memory manager, and its consequences, in https://github.com/numba/numba/pull/5857.

**Comment by pentschev** [comment]
Thanks @gmarkall , those changes make sense to me, it's great to have it documented!
