### ISSUE TITLE
LocalCUDACluster doesn't use multiple GPUs when cuDF is import

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#32]
Only the first GPU is used when importing cudf. If I remove that import, all GPUs get assigned work to do.

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import numpy as np
import cupy
import dask
import dask.array as da
import cudf

if __name__ == '__main__':
    cluster = LocalCUDACluster()
    client = Client(cluster)

    x = cupy.random.random((100000, 1000))
    d = da.from_array(x, chunks=(10000, 1000), asarray=False)
    u, s, v = np.linalg.svd(d)
    s, v = dask.compute(s, v)
```

Obviously, this example is not really using cudf for anything, just serving for demonstration purposes.

The only workaround I found for this is to start `dask-scheduler` and `dask-cuda-worker` outside of my python script. Am I missing something or doing something wrong?

**Comment by randerzander** [comment]
@pentschev if I create my LocalCUDACluster and import cudf _afterwards_, I don't get the same issue.

Basically, my workflow does things with dask_cudf first, then does some single GPU work, then goes back to dask_cudf. In my experiments, I see multiple GPUs being used as expected.

@kenhester fyi

**Comment by kkraus14** [comment]
@mrocklin @quasiben FYI. I imagine this has to do with importing cudf creating a CUDA context on GPU 0 and then the dask workers inheriting something based on this.

**Comment by quasiben** [comment]
I tried the following simple script which returns `CUDA_VISIBLE_DEVICES` from each worker and the response confirms that each worker is pointing at a unique GPU.  (This dgx machine has 8 machines)

```python
import cudf
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import numpy as np
import dask
import dask.array as da
import cupy


def get_env():
    import os
    return os.environ.get("CUDA_VISIBLE_DEVICES", None)

if __name__ == '__main__':
    cluster = LocalCUDACluster()
    client = Client(cluster)

    print(get_env())
    print(client.submit(get_env).result())
```

I wonder if this is an cudf/cupy interaction issue ?  I have recently been getting linking errors with arrow depending on the order of import for cupy/cudf

**Comment by pentschev** [comment]
@randerzander yes, I think I tried the same a couple of days ago and it also worked, but for a bit more complex code paths it can get difficult to make things work properly. Also, this is counterintuitive from the user's perspective, it took me several hours to be able to isolate the problem.

@kkraus14 I also imagine it must be something related to the context creation of cudf. Since I haven't yet touched cudf code at all, I could look into fixing that if you give me some guidelines on where to start.

@quasiben the `CUDA_VISIBLE_DEVICES` only shows what GPUs _can_ be utilized during the execution, not necessarily that they are indeed in use. In fact, if you modify the code to print `CUDA_VISIBLE_DEVICES`, then paste that CuPy code from my from my original post on this issue and then print `CUDA_VISIBLE_DEVICES` again, you'll see all GPUs are printed both before and after the CuPy code block.

**Comment by kenhester** [comment]
I also ran a similar test and each worker has a unique GPU.  A call to cudf to read a file range only happened on the first gpu before creating workers.  So all reads happened on the same gpu regardless of what was reported in the os.environ.

Ken Hester | NVIDIA Solutions Architect
c: 832-216-8736
khester@nvidia.com<mailto:khester@nvidia.com>

**Comment by VibhuJawa** [comment]
I am facing the same error without any `cudf` import in the nightly release as well as `0.7 release`.

Minimum Example:
```python
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster
import dask_cudf

def generate_file(output_file,rows=100):
    with open(output_file, 'wb') as f:
        f.write(b'A,B,C,D,E,F,G,H,I\n')
        f.write(b'22,697,56,0.0,0.0,0.0,0.0,0.0,0.0\n'*(rows))
        f.close()


if __name__ == '__main__':
    generate_file('test.csv',rows=100_000_000)
    print("generated file")

    cluster = LocalCUDACluster(ip='0.0.0.0')
    client = Client(cluster)
    print(client)
    
    df = dask_cudf.read_csv('test.csv')
    print("length of df = {:,} ".format(len(df)))
```

Nvidia-smi shows that a only the first GPU is used.

**Comment by mrocklin** [comment]
Can I ask you to print out `cluster.new_spec`

```python
import pprint
pprint.pprint(cluster.new_spec)
```

I'm looking to see if `dask_cuda.initialize_context` is in there or not.

**Comment by mrocklin** [comment]
The background here is that when profiling UCX work we found something similar and learned that CUDA contexts behaved oddly based on when they were created before threads were made or not.  I can't say I really understand what's going on there, but there are commits in master that resolved the problem for us.  I'm curious if they're in your install as well.

**Comment by VibhuJawa** [comment]
I am getting 

> Can I ask you to print out `cluster.new_spec`
> 
> ```python
> import pprint
> pprint.pprint(cluster.new_spec)
> ```
> 
> I'm looking to see if `dask_cuda.initialize_context` is in there or not.

I am getting below error, so i guess `dask_cuda.initialize_context   ` is not there. 

```python
AttributeError: 'LocalCUDACluster' object has no attribute 'new_spec'
```
Let me build `dask-cuda` from source and try my example again. Will report back results.

**Comment by VibhuJawa** [comment]
So, I am still facing the  single-gpu problem even with the latest build from master. 

```python
pprint.pprint(cluster.new_spec)
```
Output:
```python
'cls': <class 'distributed.nanny.Nanny'>,
 'options': {'dashboard_address': None,
             'data': (<class 'dask_cuda.device_host_file.DeviceHostFile'>,
                      {'device_memory_limit': 17071734784,
                       'local_dir': '/notebooks/xxxxx',
                       'memory_limit': 67619300864.0}),
             'interface': None,
             'local_dir': None,
             'memory_limit': 67619300864.0,
             'ncores': 1,
             'preload': ['dask_cuda.initialize_context'],
             'protocol': 'tcp://',
             'security': None,
             'services': {},
             'silence_logs': 30}}

```

**Comment by mrocklin** [comment]
In that case I personally don't know.  How cuda context state gets passed around is a bit beyond me I'm afraid.

**Comment by pentschev** [comment]
@VibhuJawa you're not importing `cudf` directly, but you are importing it indirectly when you `import dask_cudf`. I think this is where the context is coming from.

**Comment by VibhuJawa** [comment]
@pentschev  . Got it. Thanks for replying. 

IIRC this used to work in earlier versions though.

**Comment by kkraus14** [comment]
Could someone do a brief writeup of what information is passed from the Client process to the workers when they're instantiated? I.E. if I import cudf or pandas before creating a `LocalCUDACluster` what does that cause the workers to run during their initialization related to those codebases?

**Comment by mrocklin** [comment]
By default Dask uses the multiprocessing forkserver context.  This means that it spawns a new completely fresh process, imports `distributed` and then forks from that relatively clean process.  No other state from the client process should be transferred over, as far as I am aware.  

Recently (ten days ago) due to the UCX work we also started intentionally adding a preload script that created a CUDA context whenever the worker started up.  This uses Numba.

https://github.com/rapidsai/dask-cuda/blob/00258bbb2cff49376c2a4493ca9bbae32f61ffb3/dask_cuda/local_cuda_cluster.py#L101-L103

https://github.com/rapidsai/dask-cuda/blob/branch-0.8/dask_cuda/initialize_context.py

**Comment by mrocklin** [comment]
> No other state from the client process should be transferred over, as far as I am aware.

Although, just to be clear, I wouldn't trust that I know what I'm talking about here.  Given all the issues we've been seeing about CUDA context state I'm quite likely incorrect.  This may require someone to investigate.

**Comment by pentschev** [comment]
Given that there has been extensive usage of `LocalCUDACluster` with cuDF in multiple GPUs recently, I believe this has been solved, closing.
