### ISSUE TITLE
NVLink issues without RMM

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#332]
Recently some users have been testing out dask-cuda with ucx.  They were interested in using NVLink/CUDA-IPC and hit OOM errors.  The resolution here is usually asking the user to define an RMM pool on the workers (possibly the scheduler as well).  In the [important notes](https://dask-cuda.readthedocs.io/en/latest/ucx.html?highlight=rmm#important-notes) section we recommend using `rmm_pool` but this may be easily overlooked and/or user may be unaware when initially using these tools.  Is there something we could do to improve things ?  More/Louder documentation ?  Warning the user if `rmm_pool` is not defined ?  A requirement to use `rmm_pool` if NVLink or Infiniband is enabled ?

**Comment by pentschev** [comment]
> Warning the user if rmm_pool is not defined 

I think a warning when `enable_nvlink=True` would be fine, we can't force users to specify `rmm_pool_size` as it's perfectly acceptable that users do that via `client.run` if they have more specific needs.

**Comment by jakirkham** [comment]
Just a note, other pools would work here as well. CuPy for example uses its own memory pool by default, which likely doesn't have issues here.

**Comment by pentschev** [comment]
> Just a note, other pools would work here as well. CuPy for example uses its own memory pool by default, which likely doesn't have issues here.

Possibly, but this is untested.
