### ISSUE TITLE
Odd `__version__` reported

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-cuda#336]
Appears the version may not be working correctly here.

```python
In [1]: import dask_cuda                                                        
    
In [2]: dask_cuda.__version__                                                   
Out[2]: '0+unknown'
```

**Comment by quasiben** [comment]
Seeing the same as well from conda and from pypi but not from source

**Comment by pentschev** [comment]
I can confirm this is still an issue with conda packages, but installing from source works properly.

**Comment by jakirkham** [comment]
I think PR ( https://github.com/rapidsai/dask-cuda/pull/448 ) should address this.

**Comment by jakirkham** [comment]
With the new packages, this is now reported correctly.

```python
In [1]: import dask_cuda

In [2]: dask_cuda.__version__
Out[2]: '0.17.0a+46.ge77a3fe'
```

**Comment by jakirkham** [comment]
Reopening as we had to revert part of PR ( https://github.com/rapidsai/dask-cuda/pull/448 ) with PR ( https://github.com/rapidsai/dask-cuda/pull/466 ) as it was breaking PyPI uploads. See issue ( https://github.com/pypa/warehouse/issues/8891 ) for more context as to why that is. Am reopening this as the issue presents (at least based on my local testing) with that reversion. Will need to figure out another way forward that doesn't breaking PyPI uploads and does include the version.

**Comment by jakirkham** [comment]
This is still an issue. We tried to fix it, but the fix broke package building and uploading. So we had to revert. Need to investigate a new fix

**Comment by pentschev** [comment]
Just for a quick update, this issue still remains.

**Comment by jakirkham** [comment]
cc @wence-
