### ISSUE TITLE
[FEA] Support RMM managed memory during cluster startup via the command line

### ISSUE THREAD

**Issue by beckernick** [rapidsai/dask-cuda#341]
Today, I can set up a Dask cluster via the CLI that includes a configurable RMM pool size via `--rmm-pool-size`. This ultimately calls down to the RMMPool class to initialize RMM. This class explicitly sets up an RMM pool with `managed_memory=False`.

https://github.com/rapidsai/dask-cuda/blob/b24567d0cc3be7570f19b3bd5fe8d31d4591b623/dask_cuda/utils.py#L31-L41

It would be very nice if we could also configure RMM to use managed memory via the command line.

**Comment by pentschev** [comment]
I'm +1 on this feature. I'll try to send a PR later today for it.

**Comment by pentschev** [comment]
It's also never too much to remind people, using managed memory is incompatible with UCX+NVLink today. This is just something to keep in mind.

**Comment by beckernick** [comment]
> I'm +1 on this feature. I'll try to send a PR later today for it.

Thanks Peter!

> It's also never too much to remind people, using managed memory is incompatible with UCX+NVLink today. This is just something to keep in mind.

Never can be too careful :)
