### ISSUE TITLE
XArray in Dask-CUDA CI

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#344]
@jacobtomlinson has been exploring adding more [GPU functionality with xarray](https://github.com/pydata/xarray/issues/4212) and in PR https://github.com/pydata/xarray/pull/4214 he has added initial CuPy tests.  I'd like to ask if dask-cuda can support this effort by running xarray GPU tests in the CI similar to how we test [distributed](https://github.com/rapidsai/dask-cuda/blob/branch-0.15/ci/gpu/build.sh#L109-L110) -- I do not expect this tests to be overly onerous and lengthy.

**Comment by pentschev** [comment]
@jacobtomlinson have briefly chatted earlier today and we'll work on having tests run nightly on our DGXs, just as we do for multi-GPU tests for dask-cuda and UCX-Py. Jacob suggested as well that we report failures automatically to GH in the form of issues, and to prevent many false positives we might come up with a secondary repo just for the automated reporting, which will give us a chance to parse them and file appropriate issues for the appropriate project.

**Comment by pentschev** [comment]
For broader visibility, [NEP-35](https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html) should be part of NumPy 1.20, which will allow us to unblock parts of this.

**Comment by jakirkham** [comment]
NumPy 1.20 is out. Though guessing we still need fixes to Dask

**Comment by pentschev** [comment]
We have some `xarray` tests running nightly and being reported in https://github.com/pentschev/ucx-py-ci/issues/5 . We could extend those eventually though.

**Comment by jakirkham** [comment]
Gotcha. Thanks Peter! So in that case, maybe we should close and open new issues for any additional needed tests. WDYT?

**Comment by pentschev** [comment]
I'm fine either way, but I don't know now what are the additional needed tests. 🙂

**Comment by jakirkham** [comment]
In that case, let's close. We have some testing. If we need more, we can add them to the repo you've already setup
