### ISSUE TITLE
[DOC] Document async ways to work with dask-cuda

### ISSUE THREAD

**Issue by mengdong** [rapidsai/dask-cuda#347]
dask.distributed support [async python API](https://docs.dask.org/en/latest/setup/python-advanced.html)

Could we documentation configuration that related to dask-cuda that can be used when launching cluster through dask.distributed async python API?

**Comment by pentschev** [comment]
Hi @mengdong , as you may have already seen on our private slack some replies regarding your question, and we usually recommend using `LocalCUDACluster` for single-node setups and `SSHCluster` for multi-node setups. Is there a reason why you couldn't use one of those for your case?

**Comment by pentschev** [comment]
This has stalled, please feel free to reopen if there's still something you'd like to discuss @mengdong .
