### ISSUE TITLE
dask_cuda seems not using GPU(s)

### ISSUE THREAD

**Issue by garanews** [rapidsai/dask-cuda#38]
I have a code working dask and want run over GPU(s).
Tried to import required libraries:
`from dask.distributed import Client`
`from dask_cuda import LocalCUDACluster`
`from dask.distributed import Client`

Then initialize with: 
`if __name__ == "__main__":`
`cluster = LocalCUDACluster()`
` client = Client(cluster)`

But it seems is still using the CPU(s)
I found  https://github.com/rapidsai/dask-cuda/issues/32 , devices are seeing by system and with  nvidia-smi I see python processes passed to GPU:
![immagine](https://user-images.githubusercontent.com/16938405/56900387-000cfa80-6a96-11e9-935a-16377b57cff4.png)

But GPU(s) load remains at 0%:
![immagine](https://user-images.githubusercontent.com/16938405/56900409-0ef3ad00-6a96-11e9-9357-f8088acfd4db.png)

FYI if I try tensorflow I am able to see load over all GPU(s)

**Comment by mrocklin** [comment]
Are you using Dask to distribute computations from CUDA enabled libraries?  If not then I wouldn't expect any GPU activity.

**Comment by pentschev** [comment]
As per @mrocklin's comment, you indeed need to use some CUDA-enabled library (e.g., CuPy). You could try running the example from the description of #32, but remove `import cudf` to ensure the work is distributed among all GPUs. For that example you need at least NumPy version 1.16.x and CuPy 6.0.0b3 or 6.0.0rc1, and you will need to have the environment variable `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1` exported.

**Comment by garanews** [comment]
what do you mean?

**Comment by mrocklin** [comment]
I've updated the README here: https://github.com/rapidsai/dask-cuda#what-this-is-not

@garanews please let me know if that does not clarify things

**Comment by garanews** [comment]
The function I want send to cuda uses numpy (some np.sum, np,maximum, np.minimum, etc)
I put code here: https://gist.github.com/garanews/cbafd70717b97b7cb627703f744f6eac

**Comment by mrocklin** [comment]
NumPy doesn't use the GPU, so it's not surprising that you're not seeing any GPU activity.  It sounds like you're looking for a project that automatically converts your Python code to run on GPUs.  This project doesn't do that.  Closing this for now.  

You might want to read about some of the experimental work with Dask and CuPy on the Dask blog.

**Comment by garanews** [comment]
Okay now is clear, I have to convert my numpy in cupy.
Thanks

**Comment by mrocklin** [comment]
Correct (or PyTorch or Tensorflow or Jax or any of the other Numpy GPU libraries, but CuPy is maybe the most familiar).  

Good luck!

**Comment by garanews** [comment]
Well, tensorwlow I tried but is not performing so good for what I need, regarding cupy I am reading this https://docs-cupy.chainer.org/en/v6.0.0rc1/reference/comparison.html
and it seems there is almost everything I need, just frombuffer is still not supported, thinking how to play around it.

**Comment by garanews** [comment]
Hi @pentschev , after @mrocklin suggestion, I am trying to convert my code to use cupy: https://gist.github.com/garanews/4df9f348aa0e3872edcd7f0883677e04
It works and it is using GPU, but only one.
I removed import cudf, installed numpy 1.16.3 and cupy 6.0.0rc1 and do export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1
but still using only one GPU.
Do you have any idea?
Thanks

**Comment by pentschev** [comment]
Unfortunately, this example is too long and complex to reproduce, plus it has external dependencies, such as your database. However, I can see that you're only using cupy directly, and that alone won't distribute the work, you need to wrap your cupy array into a dask array and run your computation on the dask array. From #32:

```python
    x = cupy.random.random((100000, 1000))
    d = da.from_array(x, chunks=(10000, 1000), asarray=False)
```

After this point, you should then run your computation on the `d` array, and not anymore on the `x` array.
