### ISSUE TITLE
Perform check for unique GPU assignments in LocalCUDACluster

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/dask-cuda#384]
Many RAPIDS projects that use Dask for MNMG are likely using `LocalCUDACluster` to some capacity in automated tests. Recently, we had a bug surface in Numba which manifest itself in cuML through NCCL, and had many folks thinking NCCL was broken. 

The real culprit was a very subtle detail in the worker->GPU assignments in Dask. This detail is so subtle, in fact, that I think can easily get overlooked as different projects dig through details in their use of Dask to diagnose the cause. It would be nice if the `LocalCUDACluster` could perform a simple check that all the GPUs on the cluster are, in fact, unique, and maybe issue a warning when they are not. Maybe this method could even be exposed to the user so they can check whether the mappings are unique even when they've used the `dask-cuda-worker` script to create their workers instead of the `LocalCUDACluster`. 

In order to verify uniqueness, I've been using Numba's `get_device_identity()` method, but I'm sure there are other methods in different libraries that would work as well. I'm thinking maybe a simple `client.run` after the `LocalCUDACluster` is initialized and then a verification of uniqueness:
```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import numba.cuda
cluster = LocalCUDACluster()
client = Client(cluster)
def get_dev():
  return numba.cuda.gpus[0]._device.get_device_identity()
n_gpus_unique = len({tuple(a.values()) for a in client.run(get_dev).values()})
n_workers = len(client.scheduler_info()['workers'])
if n_gpus_unique != n_workers:
    logger.warn("Dask workers are each expected to use their own GPU device, but there are multiple workers mapped to the same device. This will cause unexpected results.")
```

**Comment by quasiben** [comment]
Thanks for raising this @cjnolet .  Can you provide more details about what happened in the MNMG test ?  Was there an oversubscription of a GPU with multiple workers ? e.g. Worker 1 -> GPU1 Worker 2->GPU1

**Comment by jakirkham** [comment]
IIUC this was the same Numba issue ( https://github.com/numba/numba/issues/6149 ) that @gmarkall fixed in PR ( https://github.com/numba/numba/pull/6147 ).

**Comment by cjnolet** [comment]
Yep, @jakirkham's got it. I thought about this when debugging the Numba issue. It wasn't immediately obvious what was going on and I think having a warning that could be thrown automatically, and/or a method on the `LocalCUDACluster` API, would help isolate this type of issue more quickly in the future.

**Comment by jakirkham** [comment]
I think the tricky thing here is we would basically have to wait until all workers are up to perform this check, which would effectively be a sync (something I don't think we want to do). Alternatively we could provide a method for people to check this themselves. Would that be helpful?

**Comment by cjnolet** [comment]
@jakirkham, yeah a method would be fine.
