### ISSUE TITLE
Was this meant to be max?

### ISSUE THREAD

**Issue by chrisroat** [rapidsai/dask-cuda#404]
It's still early and I haven't had my coffee, but was this supposed to be max?

https://github.com/rapidsai/dask-cuda/blob/b6cfacc799e03379e1d24a0170b9240716727b01/dask_cuda/cuda_worker.py#L89

**Comment by jakirkham** [comment]
Good question. Probably. @pentschev, do you have thoughts here?

**Comment by quasiben** [comment]
My guess is that this should really be `nthreads=1` -- the general assumption for dask-cuda is 1 process 1 thread 1 GPU

**Comment by pentschev** [comment]
Yeah, I generally agree with @quasiben , perhaps that could change in the future when we use support a per-thread default stream mode.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/rapidsai/dask-cuda/pull/405 ) to just make this `1`.

**Comment by pentschev** [comment]
This has been changed in #405, closing.
