### ISSUE TITLE
Explicitly scaling up LocalCUDACluster() creates Dask workers that don't use all available GPUs.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/dask-cuda#47]
I am trying to set up a Dask multi-GPU cluster on my 48-core machine with 2 GPUs. 

Using LocalCUDACluster() gives me 2 Dask workers (2 cores). 

For my pipeline, I’d prefer to use more processes than threads, to avoid the GIL issue; to solve this, when I start more workers explicitly using cluster.start_worker(), Dask seems to start more workers, but these additional workers do not use the second GPU, i.e., only one GPU gets used. 

Any ideas on how I can fix this?

**Comment by mrocklin** [comment]
There isn’t a great answer to your question currently.  But if you wanted to do things manually you could skip LocalCUDACluster and create dask workers manually

```
CUDA_VISIBLE_DEVICES=0 dask-worker ... # use the dask-worker command line arguments as you like
CUDA_VISIBLE_DEVICES=1 dask-worker ... # use the dask-worker command line arguments as you like
dask-scheduler ...
```

Currently there is a bit of work to make things like LocalCUDACluster more configurable happening here: https://github.com/dask/distributed/pull/2675

In general though, I have no idea what’s going to happen when mixing many processes and GPUs.  Maybe this is ok?

**Comment by chinmaychandak** [comment]
So, I created workers manually. Now, I am able to use both GPUs; however, the throughput is lower than using a single GPU, because some workers go into an unresponsive event loop (and some even crash and fail to restart) either due to GIL issues or moving around large chunks of data. 

Not sure why this isn't the case when using a single GPU. Any ideas as to where the problem might be?

**Comment by mrocklin** [comment]
Unfortunately not.  It could be many things.  Without more information I doubt I'll be able to help.  Often at this stage the recommendation is to try to reduce down your situation to a minimal reproducible example.

**Comment by pentschev** [comment]
The problem reported seems largely due to communication bandwidth, which is being worked with [UCX-Py](https://github.com/rapidsai/ucx-py), possibly similar to https://github.com/rapidsai/dask-cuda/issues/216. Since this has gone stale anyway, I'm closing. Feel free to reopen if you can provide more details and an example.
