### ISSUE TITLE
Warning when running XGBoost using RAPIDS AMI on Amazon EC2 instance (G4dn.12xLarge)

### ISSUE THREAD

**Issue by 9849842** [rapidsai/dask-cuda#508]
I am using dask-cuda to run xgboost on 4 GPU's. When I start the training I get the following error:

```
/home/ubuntu/.conda/envs/rapids-stable/lib/python3.8/site-packages/distributed/client.py:3517: RuntimeWarning: coroutine 'Client._update_scheduler_info' was never awaited
  self.sync(self._update_scheduler_info)
```

I am paying for the AMI so I assumed that everything would be properly configured...

I am following the GPU training demo from xgboost: https://github.com/dmlc/xgboost/blob/master/demo/dask/gpu_training.py

**Comment by quasiben** [comment]
Did the workflow not produce the correct results?  If not, I think this is just a warning you can safely ignore but we should track down where this is coming from.

**Comment by pentschev** [comment]
This has gone stale, closing. Please feel free to reopen if there's more to be discussed here.
