### ISSUE TITLE
dask-cuda broken with master distributed

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#52]
As of https://github.com/dask/distributed/pull/269, distributed no longer supports `self.scheduler_port`.  Dask-CUDA should probably support `self.scheduler_port` and `self.scheduler.port`

cc @mrocklin

**Comment by quasiben** [comment]
Something like the following should work:

```python
    @gen.coroutine
    def _start(self, ip=None, n_workers=0):
        """
        Start all cluster services.
        """
        try:
            scheduler_port = self.scheduler.port
        except ValueError:
            # distributed throws ValueError when Server is not running
            scheduler_port = False
        if self.status == "running":
            return
        if (ip is None) and (not scheduler_port) and (not self.processes):
            # Use inproc transport for optimization
            scheduler_address = "inproc://"
        elif ip is not None and ip.startswith("tls://"):
            scheduler_address = "%s:%d" % (ip, scheduler_port)
        else:
            if ip is None:
                ip = "127.0.0.1"
            scheduler_address = (ip, scheduler_port)
        self.scheduler.start(scheduler_address)
        ...
```

**Comment by mrocklin** [comment]
Yes, there is a fair amount of churn in `distributed/deploy/` in master right now, somewhat triggered by needs here (the dgx PR is a motivator).  

I'm inclined not to fix things in dask-cuda just yet because I think that we'll need to fix again shortly afterwards.  If you're ok not running from master for a week or two that might be best.

**Comment by pentschev** [comment]
This has been fixed, closing.
