### ISSUE TITLE
memory usage of 8 GPUs is not exceeded of 8g

### ISSUE THREAD

**Issue by ntaherkhani** [rapidsai/dask-cuda#521]
Hi,
memory_limit of each GPU is 94g. but memory doesn't exceed 1g (as you can see in the following image. 
![image](https://user-images.githubusercontent.com/34975127/107562663-1eca7b80-6bae-11eb-9b24-b75bca04dfa5.png)

So, the map_partitions is processing so slow.

my setting for localcudacluster is :
**_os.environ["DASK_RMM__POOL_SIZE"] = "32GB"
    os.environ["DASK_UCX__CUDA_COPY"] = "True"  
    os.environ["DASK_UCX__TCP"] = "True"
    os.environ["DASK_UCX__NVLINK"] = "True"
    os.environ["DASK_UCX__INFINIBAND"] = "True"
    os.environ["DASK_UCX__NET_DEVICES"] = "enp1s0f0"
    
    cluster = LocalCUDACluster(
    
        protocol="ucx",
        enable_tcp_over_ucx=False,
        enable_infiniband=False,
        enable_nvlink=True,
        rmm_pool_size="64GB",
        memory_limit='auto',

    )
    
    client = Client(cluster)_**

how can I set to use more memory and doing the processes faster?
Thanks

**Comment by quasiben** [comment]
I am little confused about what is being asked here -- in the above you have the memory_limit set to `auto` which dask will then set to `TOTAL_MEMORY * min(1, nthreads / total_nthreads)` in this case, nthreads is 1.   I don't know what workflow you are trying to run -- getting a minimal reproducible example would be helpful.   Why are `map_partitions` slow ?  Is dask spilling prematurely ?


Also, you should be aware that memory limit is the host memory, `device_memory_limit` refers to the GPU.

**Comment by ntaherkhani** [comment]
Hi @quasiben and thanks for your response.
actually, I have a very big dataframe including string data, and in map-partition I am embedding the sentences of each row using bert_as_service package. 
I dont know what is the best setting for LocalCUDACluster. may you please help me to set the parameters. 
thanks

**Comment by ntaherkhani** [comment]
Hello? may somebody help me about the issue? thanks.

**Comment by pentschev** [comment]
Apologies for the late response here @ntaherkhani . First of all, the 94GB you see is the memory limit on the host (CPU memory), not GPU, as only CPU memory is presented on the default Dask dashboard, for GPU memory you'll have to look at `nvidia-smi` or use [jupyterlab-nvdashboard](https://github.com/rapidsai/jupyterlab-nvdashboard). By default, Dask-CUDA sets the limit to start spilling at 80% of a total GPU's memory (see https://dask-cuda.readthedocs.io/en/latest/specializations.html#spilling-from-device for more information). Finally, your original description is contradictory on what options you're really setting, for instance you set `os.environ["DASK_RMM__POOL_SIZE"] = "32GB"` and later `rmm_pool_size="64GB"`. It's also important to notice that the RMM pool must be a little smaller than the total GPU memory (usually 90-95%), and RMM will automatically allocate that amount of memory on the GPU so you won't know exactly how much memory is in use by just looking at the GPU memory consumption.

**Comment by pentschev** [comment]
This has gone stale, closing. Please feel free to reopen if there's more to be discussed here.
