### ISSUE TITLE
Add minimal example of dask-cuda command line cluster setup

### ISSUE THREAD

**Issue by beckernick** [rapidsai/dask-cuda#554]
In the docs, we have a clear [example](https://dask-cuda.readthedocs.io/en/latest/worker.html) of setting up a LocalCUDACluster. We also list several additional arguments to the "Command Line Tool", which corresponds to the [Dask CLI](https://docs.dask.org/en/latest/setup/cli.html). However, it's not obvious from the dask-cuda documentation what needs to change relative to standard usage of the Dask CLI. We have an example of using `dask-cuda-worker` in the [UCX integration setup](https://dask-cuda.readthedocs.io/en/latest/ucx.html#usage), but it's quite possible a user wouldn't look at the UCX integration if they aren't already planning to use UCX.

It would be valuable if we included a minimal example of setting up a multi-node cluster (or equivalent single-node setup) with `dask-cuda-worker` from the command line, like in the Dask docs. This could live in either dask-cuda or dask. This documentation would be a valuable asset to share with users interested in testing multi-node or from the command line.

**Comment by pentschev** [comment]
Just recently @charlesbluca added some code to try and address specifically that, which now lives in https://github.com/rapidsai/dask-cuda/tree/branch-0.19/examples/ucx . Does that cover your question, if not, what else could we do to improve it?

**Comment by charlesbluca** [comment]
Maybe it would be better to duplicate some of the general usage info in the UCX section in the Worker section, so that it's more visible? We can always slim down the UCX section later on if we find that parts of it are redundant.

I'm also happy to expand upon the standalone utilities - if we made the use of UCX an option, then they could function as a minimal example of a standard multi/single-node set up.

**Comment by beckernick** [comment]
@charlesbluca I think that approach would be a great idea

**Comment by charlesbluca** [comment]
Currently drafting some changes to address the docs aspect of this in #561 - in general, I am leaning towards putting basic usage examples in the first few pages, and moving more advanced configuration to standalone examples in the docs.

**Comment by jakirkham** [comment]
Is this resolved with PR ( https://github.com/rapidsai/dask-cuda/pull/561 ) or was there more work needed here?

**Comment by charlesbluca** [comment]
I think that's sufficient - we could always potentially add an example script like [those made for UCX](https://github.com/rapidsai/dask-cuda/tree/branch-0.20/examples/ucx).

@beckernick did you get a chance to check out the changes to the docs?

**Comment by pentschev** [comment]
I guess this is mostly addressed and since this has been inactive for so long I'm gonna close it for now, but please reopen/file a new issue if needed.
