### ISSUE TITLE
[DOCS] missing CLI params

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/dask-cuda#560]
Looks like a bunch of the CLI params @ https://github.com/rapidsai/dask-cuda/blob/branch-0.19/dask_cuda/cli/dask_cuda_worker.py (ex: `--nthreads`) are not in https://github.com/rapidsai/dask-cuda/blob/branch-0.19/docs/source/worker.rst  . I'm fine looking at code, but maybe a useful heads up :)

**Comment by charlesbluca** [comment]
I'm actually reworking the docs now, so I've been looking for a way to auto-generate the CLI parameter docs - thanks for pointing this out!

**Comment by charlesbluca** [comment]
Just to follow up on this, I think [click-contrib/sphinx-click](https://github.com/click-contrib/sphinx-click) should be perfect for this.

**Comment by charlesbluca** [comment]
This *should* be resolved with the next release, as the CLI param docs are now autogenerated:

- https://github.com/rapidsai/dask-cuda/blob/branch-0.20/docs/source/api.rst#worker

Thanks for bringing this up!
