### ISSUE TITLE
Add Conda environment files for development

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/dask-cuda#569]
As I'm remaking some of my dev environments, I noticed that dask-cuda doesn't seem to have an environment file for development - there is the [requirements.txt](https://github.com/rapidsai/dask-cuda/blob/branch-0.20/requirements.txt) and some dependencies listed implicitly in the [Conda recipe](https://github.com/rapidsai/dask-cuda/blob/branch-0.20/conda/recipes/dask-cuda/meta.yaml), but those don't seem to include some of the other requirements for testing or build docs.

Is there a dev environment file I'm missing? If not, would it be feasible/useful to add one? Not sure if we would need to add multiple for different versions of CUDA toolkit like [cuDF's case](https://github.com/rapidsai/cudf/tree/branch-0.20/conda/environments).

**Comment by pentschev** [comment]
Generally this isn't a requirement because we're not really building anything from source (unlike cuDF), so the instructions from the [RAPIDS Getting Started](https://rapids.ai/start.html) page are also sufficient for a dev environment.

Are you suggesting a specialized use case for which the instructions from the link above doesn't cover? If so, which one would that be?

**Comment by charlesbluca** [comment]
I suppose cuDF isn't really the best example since the environment there is necessity rather than a convenience. I agree that the quickstart page does proper instructions on how to install the nightly build of dask-cuda, thought it may not be immediately obvious to non-RAPIDS contributors since the package isn't listed there.

The main use case I'm thinking of is if a user wants to do documentation work / full testing on dask-cuda in a minimal environment. In this case, if they followed the quickstart or dask-cuda's documentation to install it, they would still need to do some trial and error to sort out the requirements for running the full test suite, linting the codebase, or building the documentation.

**Comment by pentschev** [comment]
I would very much prefer that we document this rather than having conda environment files. The natural follow-up to that would be "How about developers that use Pip?", and this ends up with us having to maintain several files that are very seldom used.

IMO, the instructions we would need are simply:
* How to run pytests;
* How to build docs;
* Linting using pre-commit.

I don't necessarily oppose to having conda environment files for that, but I just think it's great if we can keep maintenance efforts low.

**Comment by jakirkham** [comment]
Maybe this is useful for [reusing `requirements.txt` with Conda]( https://stackoverflow.com/a/57845418 )?

**Comment by jakirkham** [comment]
We could also cutdown duplication between the recipe and `setup.py` using [`load_setup_py_data` in the recipe]( https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html?highlight=load_setup_py_data#templating-with-jinja )

**Comment by charlesbluca** [comment]
> The natural follow-up to that would be "How about developers that use Pip?"

Probably my lack of experience with Python package maintenance, but I didn't think that would be such a common question. From my perspective, the vast majority of people wanting to do dev work on dask-cuda would probably be finding it through other RAPIDS libraries or Dask(.distributed), both of which primarily use Conda and (generally) don't offer any documentation on development using exclusively Pip.

That being said, it would be a lot of maintenance to keep these files up to date. Placing this in the documentation is a possibility, but I'm a little iffy on that if it comes to telling users to install pinned/restricted versions of certain packages, as if a problem arises due to an upstream change, the documentation won't be able to reflect this until the next dask-cuda release (I think? Basing this on the fact that the docs haven't yet reflected the changes of #561), whereas an env file in the nightly branch can be immediately updated for developers.

**Comment by jakirkham** [comment]
To Peter's point we do periodically get people that just use Dask-CUDA and maybe CuPy or Numba, all of which can be installed with Conda or pip, that come by and ask questions. Keeping them happy is valuable and doesn't cost much

Libraries like cuDF have a lot of C++ code and dependencies. So trying to support pip there isn't really worth the effort. Thus they have made different decisions

I think we can probably get more out of the few files we have here and keep the maintenance burden low (or even reduce it further). For example, I'm curious if using the `requirements.txt` file with Conda ( https://github.com/rapidsai/dask-cuda/issues/569#issuecomment-819018208 ) just works, is this something you would be able to try? Are there issues that come up that we could fix relatively easily? 🙂

**Comment by charlesbluca** [comment]
I think reusing the requirements file should work, I just think it might need to be updated since it seems like it's inconsistent with the recipe. Would it be okay for that file to also contain dev requirements, or should those go in a `requirements-dev.txt`?

**Comment by charlesbluca** [comment]
> We could also cutdown duplication between the recipe and setup.py using load_setup_py_data in the recipe

I can look into this

**Comment by pentschev** [comment]
> ... Basing this on the fact that the docs haven't yet reflected the changes of #561), ...

This seems like a bug, we should be updating whenever there's an update to docs. @quasiben is this something that you have to do or do we have to raise that with ops?

**Comment by pentschev** [comment]
John's ideas also sound good to me, anything that can prevent us from changing a dozen different files anytime we need a version change is great!

**Comment by quasiben** [comment]
I just triggered a build for dask-cuda.  Both dask-cuda and ucx-py on readthedocs and we haven't spent the time to integrate a doc build action with our CI.  I don't think this would be too hard too do but would require coordinating with ops to get a build token in the CI system

**Comment by charlesbluca** [comment]
@quasiben just letting you know that it doesn't seem like the RTD site has updated since then

**Comment by jakirkham** [comment]
> We could also cutdown duplication between the recipe and `setup.py` using [`load_setup_py_data` in the recipe](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html?highlight=load_setup_py_data#templating-with-jinja)

Submitted PR ( https://github.com/rapidsai/dask-cuda/pull/893 ) along these lines. This seemed ok locally, but maybe more is needed.

**Comment by pentschev** [comment]
@charlesbluca @jakirkham do you think we can close this since #893 has been merged, or are there any tasks left?

**Comment by charlesbluca** [comment]
Yeah we should be good to close this - @jakirkham feel free to ping if you think there's something else we could do to follow up on #893

**Comment by jakirkham** [comment]
Not from me 🙂
