### ISSUE TITLE
Moving documentation to docs.rapids.ai

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/dask-cuda#579]
After some internal discussion, we have decided to move the documentation of Dask-CUDA from Read the Docs to [RAPIDS Docs](https://docs.rapids.ai/). This would make it relatively easy to set up a docs CI workflow script like [this](https://github.com/rapidsai/cudf/blob/branch-0.20/ci/docs/build.sh), and is motivated by the fact that there are a lot of barriers keeping this repo from migrating to Dask org.

What's a clean way to do this without causing confusion? Should we keep both sites up simultaneously for a period of time with some banner notifying the migration? Or have the RTD docs redirect straight to the RAPIDS docs?

cc @quasiben @pentschev

**Comment by charlesbluca** [comment]
Opened #580 to make a gpuCI docs build script.

**Comment by pentschev** [comment]
Redirecting seems like a simpler way to deal with it.

**Comment by charlesbluca** [comment]
I agree, just wasn't sure if RTD had the ability to easily manage a redirect but looks like it can.

**Comment by charlesbluca** [comment]
Dask-CUDA's docs just got published to RAPIDS docs:

- https://docs.rapids.ai/api/dask-cuda/nightly/

Now we would just want to figure out redirecting the RTD version of the docs.

**Comment by jakirkham** [comment]
In conda-forge we did this like [so]( https://github.com/conda-forge/conda-forge.github.io/tree/df804a45b7a99823f7cf6e330ff7caac07ea24e4/rtd )

**Comment by charlesbluca** [comment]
Great - thanks for that example! Do you know if we would need to keep that `rtd/` directory in our repo if we disable webhooks on RTD's end after the last build?

**Comment by jakirkham** [comment]
Peter was mentioning redirecting, which agree probably makes sense (there may be other links to RTD out there).

So the `rtd` directory is important for supplying a documentation build that creates a webpage on RTD to do the redirecting. This is set in [the RTD config file]( https://github.com/conda-forge/conda-forge.github.io/blob/df804a45b7a99823f7cf6e330ff7caac07ea24e4/.readthedocs.yaml#L3-L4 ). We wouldn't want that in our usual docs hence the separate directory.
