### ISSUE TITLE
Multi-node CUDA cluster

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/dask-cuda#58]
As cuML is beginning the venture into algorithms that span multiple nodes, it would be very useful if we had a mechanism for starting, or attaching workers to, a multi-node Dask CUDA cluster.

**Comment by pentschev** [comment]
If I understand correctly, what you would like is more of an automation tool, that controls the launching of such instances, is that correct?

In general, a Dask CUDA cluster is composed of a `dask-scheduler` and one or more `dask-cuda-worker` processes. Couldn't that be automated by something like kubernetes?

**Comment by mrocklin** [comment]
The first answer to this is that you can always set things up using normal `dask-scheduler` and `dask-worker` CLI commands.  If you have complications like multiple GPUs per node then you might want to become careful with setting CUDA_VISIBLE_DEVICES and such, but that's not hard to do.  You could also start using tools like `dask-cuda-worker` in this repository.

If you have a resource manager, like SLURM/PBS/Kubernetes/Yarn then you'll probably want to use the associated Dask project (please speak up if this is your situation).

You might also try dask-ssh, though it's a bit less loved than the other solutions.  

Maybe I should ask, @cjnolet , is there an issue in particular that you're finding inconvenient, if so, that would probably help us to figure out how best to address it.

**Comment by cjnolet** [comment]
Looking at the options currently available, the `dask-cuda-worker` appears to be what I'm after. 

Really, what I'd like to be able to do is quickly fire up a scheduler and, with a tool as easy to use as the `LocalCUDACluster`, fire up a bunch of workers on different nodes, each responsible for a single GPU, and have them connect to a single scheduler. 

If I'm not mistaken, I should be able to accomlish this with the `dask-cuda-worker`, right?

**Comment by mrocklin** [comment]
Yes, dask-cuda-worker will check for all available workers on a node, and
start up a dask-worker attached to each one.

**Comment by cjnolet** [comment]
I've been using this today to test some multi-node code. This is exactly what I needed. Thank you!

**Comment by pentschev** [comment]
> dask-cuda-worker will check for all available workers on a node

I think you meant to say it will check for all available GPUs on a node, no?

**Comment by pentschev** [comment]
> I've been using this today to test some multi-node code. This is exactly what I needed. Thank you!

Sorry, didn't see your comment, but glad it works! :)
