### ISSUE TITLE
Appending Dataframes

### ISSUE THREAD

**Issue by Data-drone** [rapidsai/dask-cuda#588]
I have two dataframes with the same columns that I am trying to append.

When I run

```
df1.append(df2) 
```

I get: `TypeError: concat_cudf() got an unexpected keyword argument 'ignore_order'`

this is on version `0.18.2`

**Comment by pentschev** [comment]
This is due to a change in Dask https://github.com/dask/dask/pull/7473 that was fixed in https://github.com/dask/dask/pull/7500 . Could you make sure you have Dask and Distributed version `2021.04.0`?

Also, for future reference, cuDF issues should be raised in https://github.com/rapidsai/cudf .

**Comment by pentschev** [comment]
This has gone stale, closing. If you still have issues, please feel free to reopen.
