### ISSUE TITLE
Adding functionality for spilling to packed device memory

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/dask-cuda#601]
I am currently working on a Python API for cuDF pack/unpack (rapidsai/cudf#8153), with the goal being to add functionality here to spill to packed device memory.

Currently, this API allows for something like:

```python
gdf = cudf.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
packed = pack(gdf)         # returns a PackedColumns object
unpacked = unpack(packed)  # returns a cudf DataFrame
```

Is there anything else we would want in this API to open it up for use here?

cc @madsbk @pentschev

**Comment by pentschev** [comment]
From a "standard" spilling perspective, today things work as follows: `Device<->Host<->Disk`. To add this into that workflow, I think it would be as simple as adding a new layer: `(Pack/Unpack)<->Device<->Host<->Disk`. There's also the JIT spilling which is considerably more complex and @madsbk would be best suited to comment, but I believe the new `(Pack/Unpack)` layer could be added to the workflow in the same way as the standard spilling: `(Pack/Unpack)<->(JIT Spill/Unspill)<->...` .

Of course, all of the above is meant as an initial implementation for evaluation of the functional aspects. We would probably want to evaluate whether combining some of these layers would lead to improved performance and a simple codebase too.

**Comment by charlesbluca** [comment]
That idea of a new layer makes sense - I seem to recall from the last stand up the potential to maybe spill to packed memory first, so something like `unpacked dev<->packed dev<->host<->disk`.  However, I think for right now it would make more sense to implement in the way you've laid out.

My biggest concern here is the return type of [`host_to_device()`](https://github.com/rapidsai/dask-cuda/blob/1d71749c6eed12ec60e175183c40300dcad914f3/dask_cuda/device_host_file.py#L140-L142), since I'd imagine that's what we'd want to pass into some hypothetical `device_to_packed()` function. Currently, the [C++ API for `pack`](https://github.com/rapidsai/cudf/blob/99df69fb7e1c61c2cf8a0a405d2885438dc0a7c3/cpp/include/cudf/copying.hpp#L583-L584) only allows `table_views` for input, meaning that we are limited to packing cuDF DataFrames. Should we perform a check in this packed spilling function to ensure that the object we are receiving as input is a DataFrame, or would the C++ API need to be expanded to even allow functionality here?

**Comment by charlesbluca** [comment]
I'm not sure I understand - do you mean implement host<->device spilling for DataFrames on cuDF's end, or device<->packed?

**Comment by jakirkham** [comment]
Am referring to [these methods]( https://github.com/rapidsai/cudf/blob/348ad4dcdd1cc7f970241d4389493176cd58dd5a/python/cudf/cudf/core/dataframe.py#L555-L586 ). Ideally packing/unpacking would be done there and Dask wouldn't need to know anything about it

**Comment by charlesbluca** [comment]
Ah thanks for the clarification - that makes sense. Would that mean that we wouldn't have an unpacked device layer, and that spilling DataFrames to/from device would always pack/unpack? If so, I'm wondering if we would want to keep the ability to serialize without packing by making separate functions for this (i.e. `serialize`/`deserialize_packed`).

**Comment by jakirkham** [comment]
Yeah this came up in issue ( https://github.com/rapidsai/cudf/issues/7601 ). Basically we might want a config for cuDF ( https://github.com/rapidsai/cudf/issues/5311 ), which could enable/disable packing

**Comment by pentschev** [comment]
I agree with @jakirkham 's idea too, having this in cuDF itself is a much better alternative, and allows Dask-CUDA to abstract that change, as well as letting pure Dask users to enjoy that compression mechanism as well.

**Comment by jakirkham** [comment]
cuDF uses these functions when pickling objects as well, which is not Dask specific. So it probably makes more sense to have the config somewhere cuDF users can control

**Comment by charlesbluca** [comment]
Closing this as the solution forward here is making changes to cuDF 🙂
