### ISSUE TITLE
Raise errors in CI on `dask` / `distributed` deprecations

### ISSUE THREAD

**Issue by jrbourbeau** [rapidsai/dask-cuda#666]
There's been interest from some Dask maintainers and folks on the RAPIDS team in Dask being more explicit about its public API. As a result we've started deprecating some utilities in `dask` and `distributed` (xref https://github.com/dask/distributed/pull/4966, https://github.com/dask/dask/pull/7810) and will eventually start making some methods private by prepending a leading underscore (`_`) to their name. We're planning to do this transition smoothly by raising `FutureWarning`s / `DeprecationWarning`s ahead of time to inform Dask users of any upcoming changes. 

In light of this, is there any interest for `dask-cuda` (or other RAPIDS projects which use Dask) to start raising errors in CI on `FutureWarning`s / `DeprecationWarning`s which are raised from `dask` or `distributed`? This will help give `dask-cuda` developers a heads up on upcoming changes. 

cc @rjzamora

**Comment by pentschev** [comment]
Sorry for the delay here @jrbourbeau . I think this is generally a good idea, although this may become a burden if some of the other dependencies decide to start emitting too many of those. I've opened #672 so we can experiment with that for a while.
