### ISSUE TITLE
On 4 GPU system a few dask_cuda tests fail

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/dask-cuda#668]
Using nightly 21.08:

```
AssertionError: assert False
 +  where False = wait_workers(<Client: 'tcp://192.168.254.2:9369' processes=0 threads=0, memory=0 B>, n_gpus=1)
 +    where 1 = get_n_gpus()
Stacktrace
Traceback (most recent call last):
  File "/h2oai/dask-cuda/dask_cuda/tests/test_dask_cuda_worker.py", line 129, in test_rmm_async
    assert wait_workers(client, n_gpus=get_n_gpus())
AssertionError: assert False
 +  where False = wait_workers(<Client: 'tcp://192.168.254.2:9369' processes=0 threads=0, memory=0 B>, n_gpus=1)
 +    where 1 = get_n_gpus()
```

```
Error Message
AssertionError: assert False
 +  where False = wait_workers(<Client: 'tcp://192.168.254.2:9369' processes=0 threads=0, memory=0 B>, n_gpus=1)
 +    where 1 = get_n_gpus()
Stacktrace
Traceback (most recent call last):
  File "/h2oai/dask-cuda/dask_cuda/tests/test_dask_cuda_worker.py", line 102, in test_rmm_managed
    assert wait_workers(client, n_gpus=get_n_gpus())
AssertionError: assert False
 +  where False = wait_workers(<Client: 'tcp://192.168.254.2:9369' processes=0 threads=0, memory=0 B>, n_gpus=1)
 +    where 1 = get_n_gpus()
```

```
Error Message
AssertionError: assert False
 +  where False = wait_workers(<Client: 'tcp://192.168.254.2:9359' processes=0 threads=0, memory=0 B>, n_gpus=4)
Stacktrace
Traceback (most recent call last):
  File "/h2oai/dask-cuda/dask_cuda/tests/test_dask_cuda_worker.py", line 42, in test_cuda_visible_devices_and_memory_limit_and_nthreads
    assert wait_workers(client, n_gpus=4)
AssertionError: assert False
 +  where False = wait_workers(<Client: 'tcp://192.168.254.2:9359' processes=0 threads=0, memory=0 B>, n_gpus=4)
```

**Comment by pentschev** [comment]
Could you post the output of `conda list`, the command line you're using to run the tests and whether this is running on baremetal, docker or some other form?

**Comment by pseudotensor** [comment]
[conda_list.txt.zip](https://github.com/rapidsai/dask-cuda/files/6779413/conda_list.txt.zip)

With conda, run on jenkins machine for testing, but same installation as given here.  When run on jenkins, it is run inside a docker image with cuda 11.2 with this conda setup installed.

**Comment by pentschev** [comment]
Unfortunately, I wasn't able to reproduce the issue on my end so far. Are those failures deterministic? They are all happening at [`wait_workers`](https://github.com/rapidsai/dask-cuda/blob/63b4646eee17cb2d32eab1102151ccc85052f8cb/dask_cuda/utils.py#L369-L410) which has a predefined timeout of `max(10, 2 * N_GPUs)` seconds. I believe it could be that this is just taking longer on your system for some reason. Would you be able to try out longer timeouts?

**Comment by pseudotensor** [comment]
Hi @pentschev , thanks for checking.  Yes, they happen every time for a given system.  For now I've just skipped the tests since it keeps coming up.

If you have some way for me to debug I'm happy to try.

**Comment by pentschev** [comment]
What I suggest is trying to change the lines where the error is reported perhaps to `wait_workers(..., min_timeout=60)`. Normally it would probably be overkill to set to 60 seconds, but if it passes then it at least confirms that it's a timeout issue when waiting for workers.

**Comment by pentschev** [comment]
This is inactive without response from original poster, I'm closing but please reopen if still relevant.
