### ISSUE TITLE
Move to dask org

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cuda#69]
This project is more closely tied to Dask projects than RAPIDS projects, particularly with dependencies and release cycles.  Should we move it from the rapidsai organization to the dask org?

One challenge is that we still need GPU CI for testing PRs.  Is that likely to cause an issue with this process?

**Comment by mrocklin** [comment]
cc @raydouglass

**Comment by mrocklin** [comment]
Actually I think that my ideal would be to keep things in this github organization, but to handle the release process similar to non-rapids libraries, using conda-forge as the distribution channel and timing releases with dask rather than rapids.

**Comment by raydouglass** [comment]
cc @mike-wendt

**Comment by pentschev** [comment]
I have no strong feelings about release schedule, but I strongly oppose to moving anything that requires GPU CI outside of this org. The RAPIDS CI team already does a great job maintaining it, and I fear that repos outside this org will have reduced visibility (from a RAPIDS perspective) and end up with lower priority.

**Comment by jakirkham** [comment]
I think we've decided to keep things as they are. We can revisit if needed
