### ISSUE TITLE
LocalCUDACluster error in environment without UCX

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/dask-cuda#728]
With the latest nightly (21.10) creating a `LocalCUDACluster()` fails if ucx is not present in the environment.

```python
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()

File "/datasets/adattagupta/miniconda3/envs/cudf/lib/python3.8/site-packages/dask_cuda/initialize.py", line 20, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/datasets/adattagupta/miniconda3/envs/cudf/lib/python3.8/site-packages/distributed/comm/ucx.py", line 50, in init_once
    ucx_config = _scrub_ucx_config()
  File "/datasets/adattagupta/miniconda3/envs/cudf/lib/python3.8/site-packages/distributed/comm/ucx.py", line 473, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
ModuleNotFoundError: No module named 'ucp'
``` 

**Expected behavior**:
`_create_cuda_context` should only depend on ucx if it's present in the environment, and allow users to create a tcp cluster without it. (Installing dask-cuda from conda doesn't include ucx by default).

**Environment Creation**:
```
conda install -c rapidsai-nightly -c nvidia -c conda-forge cudf dask-cudf dask-cuda python=3.8 cudatoolkit=11.2
```

**Comment by pentschev** [comment]
Thanks for the report @ayushdg . I pushed #729 to fix this.

**Comment by jakirkham** [comment]
Thanks Peter! 😄

The traceback above also points to [this line in Distributed]( https://github.com/dask/distributed/blob/05677bb2be375231d563bc099624965d7e1bc4b1/distributed/comm/ucx.py#L508 ). Should we be looking at that as well?

**Comment by pentschev** [comment]
That case is covered as well, whoever raises `ModuleNotFoundError` will be catched and skipped in https://github.com/rapidsai/dask-cuda/pull/729/files#diff-a1418fdbfff5b6dc0b4ab0c43d9492a8beef860adab716af81e88a90901e8ea9R22 .

**Comment by jakirkham** [comment]
Ok wasn't sure if we were using `_scrub_ucx_config` anywhere else. If not, great 🙂

**Comment by pentschev** [comment]
> Ok wasn't sure if we were using `_scrub_ucx_config` anywhere else. If not, great 🙂

It is called from `init_once`, but we don't use it anywhere else, so we're good for now.

**Comment by jakirkham** [comment]
Thanks Peter 🙂 Went ahead and merged.

It will take a bit for nightlies to be produced, Ayush. Can just checkout `branch-21.10` locally or can wait a bit for the nightlies
