### ISSUE TITLE
Unable to initiate LocalCudaCluster with GPU

### ISSUE THREAD

**Issue by luyang-ai4med** [rapidsai/dask-cuda#762]
Issue description: 
I am trying to run xgboost on SLURM system (a HPC cluster). 

Steps to reproduce:
1. [Install the package following the instructions](https://developer.nvidia.com/blog/accelerating-xgboost-on-gpu-clusters-with-dask/)
`conda install -c rapidsai -c conda-forge dask dask-ml dask-cuda dask-cudf xgboost=1.4.2
2. Having problems following:
cluster = LocalCUDACluster(threads_per_worker=4) 

Traceback as following:

```
distributed.diskutils - INFO - Found stale lock file and directory '****dask-worker-space/worker-udj4gf3y', purging
distributed.diskutils - INFO - Found stale lock file and directory '******/dask-worker-space/worker-xp77379u', purging
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "******anaconda3/envs/xgbgpu/lib/python3.7/site-packages/dask_cuda/initialize.py", line 52, in _create_cuda_context
    _create_cuda_context_handler()
  File "*********anaconda3/envs/xgbgpu/lib/python3.7/site-packages/dask_cuda/initialize.py", line 24, in _create_cuda_context_handler
    numba.cuda.current_context()
  File "******/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in get_context
    return _runtime.get_or_create_context(devnum)
  File "********/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "********/software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    return self._activate_context_for(0)
  File "********anaconda3/envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 169, in _activate_context_for
    newctx = gpu.get_primary_context()
  File "********envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 525, in get_primary_context
    driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
  File "********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "********envs/xgbgpu/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.Cuda
```

Any suggestions to fix this?

**Comment by yangl57** [comment]
@pentschev Hi Peter, I started to initiate workers on another set of gpus but having problems as below. Could you please see what might go wrong? 

cluster = LocalCUDACluster(n_workers=3)
client = Client(cluster)
<img width="560" alt="nvidia-smi" src="https://user-images.githubusercontent.com/15113700/140688693-5121e81b-3c79-40c7-910d-35149075d6fd.png">

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_70687/4108086556.py in <module>
----> 1 cluster = LocalCUDACluster(n_workers=3)
      2 client = Client(cluster)

/********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py in __init__(self, CUDA_VISIBLE_DEVICES, n_workers, threads_per_worker, memory_limit, device_memory_limit, data, local_directory, shared_filesystem, protocol, enable_tcp_over_ucx, enable_infiniband, enable_nvlink, enable_rdmacm, ucx_net_devices, rmm_pool_size, rmm_managed_memory, rmm_async, rmm_log_directory, jit_unspill, log_spilling, worker_class, **kwargs)
    373         self.cuda_visible_devices = CUDA_VISIBLE_DEVICES
    374         self.scale(n_workers)
--> 375         self.sync(self._correct_state)
    376 
    377     def new_worker_spec(self):

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    212             return future
    213         else:
--> 214             return sync(self.loop, func, *args, **kwargs)
    215 
    216     def _log(self, log):

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    324     if error[0]:
    325         typ, exc, tb = error[0]
--> 326         raise exc.with_traceback(tb)
    327     else:
    328         return result[0]

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/utils.py in f()
    307             if callback_timeout is not None:
    308                 future = asyncio.wait_for(future, callback_timeout)
--> 309             result[0] = yield future
    310         except Exception:
    311             error[0] = sys.exc_info()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/deploy/spec.py in _correct_state_internal(self)
    369                 for w in workers:
    370                     w._cluster = weakref.ref(self)
--> 371                     await w  # for tornado gen.coroutine support
    372             self.workers.update(dict(zip(to_open, workers)))
    373 

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/core.py in _()
    281                         )
    282                 else:
--> 283                     await self.start()
    284                     self.status = Status.running
    285             return self

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in start(self)
    333 
    334         logger.info("        Start Nanny at: %r", self.address)
--> 335         response = await self.instantiate()
    336         if response == Status.running:
    337             assert self.worker_address

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in instantiate(self, comm)
    416         else:
    417             try:
--> 418                 result = await self.process.start()
    419             except Exception:
    420                 await self.close()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in start(self)
    690             return self.status
    691         try:
--> 692             msg = await self._wait_until_connected(uid)
    693         except Exception:
    694             self.status = Status.failed

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in _wait_until_connected(self, uid)
    809                     "Failed while trying to start worker process: %s", msg["exception"]
    810                 )
--> 811                 raise msg["exception"]
    812             else:
    813                 return msg

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in run()
    881                 """
    882                 try:
--> 883                     await worker
    884                 except Exception as e:
    885                     logger.exception("Failed to start worker")

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/core.py in _()
    281                         )
    282                 else:
--> 283                     await self.start()
    284                     self.status = Status.running
    285             return self

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/worker.py in start()
   1240         self._pending_plugins = ()
   1241 
-> 1242         await self._register_with_scheduler()
   1243 
   1244         self.start_periodic_callbacks()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/worker.py in _register_with_scheduler()
    936                             if ts.state == "memory"
    937                         },
--> 938                         types={k: typename(v) for k, v in self.data.items()},
    939                         now=time(),
    940                         resources=self.total_resources,

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/worker.py in <dictcomp>()
    936                             if ts.state == "memory"
    937                         },
--> 938                         types={k: typename(v) for k, v in self.data.items()},
    939                         now=time(),
    940                         resources=self.total_resources,

********software/anaconda3/envs/xgbgpu/lib/python3.7/_collections_abc.py in __iter__()
    741 
    742     def __iter__(self):
--> 743         for key in self._mapping:
    744             yield (key, self._mapping[key])
    745 

RuntimeError: Set changed size during iteration`

**Comment by pentschev** [comment]
This now seems like a different behavior, could you please open a new issue adding:

1. The output of `conda list` for the environment you're using on that machine; and
2. A minimal reproducer + the command you're using to run your code; and
3. The error above.
