### ISSUE TITLE
Unable to initiate LocalCudaCluster with multiple GPUs

### ISSUE THREAD

**Issue by 666-sudo** [rapidsai/dask-cuda#773]
Environment 
[conda_list.txt](https://github.com/rapidsai/dask-cuda/files/7495972/conda_list.txt)

nvidia-smi 
<img width="560" alt="nvidia-smi" src="https://user-images.githubusercontent.com/15113700/140722087-f5951938-2a89-4232-8f1b-a1da2255a852.png">

To reproduce:

from dask_cuda import LocalCUDACluster
from distributed import Client, wait

cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES = "0", n_workers=1)
client = Client(cluster)

Errors:

```
---------------------------------------------------------------------------
RuntimeError Traceback (most recent call last)
/tmp/ipykernel_70687/4108086556.py in 
----> 1 cluster = LocalCUDACluster(n_workers=3)
2 client = Client(cluster)

/********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py in init(self, CUDA_VISIBLE_DEVICES, n_workers, threads_per_worker, memory_limit, device_memory_limit, data, local_directory, shared_filesystem, protocol, enable_tcp_over_ucx, enable_infiniband, enable_nvlink, enable_rdmacm, ucx_net_devices, rmm_pool_size, rmm_managed_memory, rmm_async, rmm_log_directory, jit_unspill, log_spilling, worker_class, **kwargs)
373 self.cuda_visible_devices = CUDA_VISIBLE_DEVICES
374 self.scale(n_workers)
--> 375 self.sync(self._correct_state)
376
377 def new_worker_spec(self):

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
212 return future
213 else:
--> 214 return sync(self.loop, func, *args, **kwargs)
215
216 def _log(self, log):

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
324 if error[0]:
325 typ, exc, tb = error[0]
--> 326 raise exc.with_traceback(tb)
327 else:
328 return result[0]

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/utils.py in f()
307 if callback_timeout is not None:
308 future = asyncio.wait_for(future, callback_timeout)
--> 309 result[0] = yield future
310 except Exception:
311 error[0] = sys.exc_info()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/tornado/gen.py in run(self)
760
761 try:
--> 762 value = future.result()
763 except Exception:
764 exc_info = sys.exc_info()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/deploy/spec.py in _correct_state_internal(self)
369 for w in workers:
370 w._cluster = weakref.ref(self)
--> 371 await w # for tornado gen.coroutine support
372 self.workers.update(dict(zip(to_open, workers)))
373

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/core.py in _()
281 )
282 else:
--> 283 await self.start()
284 self.status = Status.running
285 return self

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in start(self)
333
334 logger.info(" Start Nanny at: %r", self.address)
--> 335 response = await self.instantiate()
336 if response == Status.running:
337 assert self.worker_address

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in instantiate(self, comm)
416 else:
417 try:
--> 418 result = await self.process.start()
419 except Exception:
420 await self.close()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in start(self)
690 return self.status
691 try:
--> 692 msg = await self._wait_until_connected(uid)
693 except Exception:
694 self.status = Status.failed

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in _wait_until_connected(self, uid)
809 "Failed while trying to start worker process: %s", msg["exception"]
810 )
--> 811 raise msg["exception"]
812 else:
813 return msg

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/nanny.py in run()
881 """
882 try:
--> 883 await worker
884 except Exception as e:
885 logger.exception("Failed to start worker")

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/core.py in _()
281 )
282 else:
--> 283 await self.start()
284 self.status = Status.running
285 return self

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/worker.py in start()
1240 self._pending_plugins = ()
1241
-> 1242 await self._register_with_scheduler()
1243
1244 self.start_periodic_callbacks()

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/worker.py in _register_with_scheduler()
936 if ts.state == "memory"
937 },
--> 938 types={k: typename(v) for k, v in self.data.items()},
939 now=time(),
940 resources=self.total_resources,

********software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/worker.py in ()
936 if ts.state == "memory"
937 },
--> 938 types={k: typename(v) for k, v in self.data.items()},
939 now=time(),
940 resources=self.total_resources,

********software/anaconda3/envs/xgbgpu/lib/python3.7/_collections_abc.py in iter()
741
742 def iter(self):
--> 743 for key in self._mapping:
744 yield (key, self._mapping[key])
745

RuntimeError: Set changed size during iteration
```

Could you please advise on such issues? Thank you for your help.

**Comment by pentschev** [comment]
There are discrepancies from the minimal reproducer to the error you pasted. Could you confirm you see the exact same error with the minimal reproducer? Plus, if you're running that from `python`, it will error anyway, you need to ensure `LocalCUDACluster` is only created on the main process, therefore it should look something like:

```python
from dask_cuda import LocalCUDACluster
from distributed import Client, wait

if __name__ == "__main__":
    cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES = "0")
    client = Client(cluster)
```

Also note that `n_workers` will override `CUDA_VISIBLE_DEVICES`, [see this](https://docs.rapids.ai/api/dask-cuda/nightly/api.html#dask_cuda.LocalCUDACluster).

I can also see that the source channel for many of your packages is unknown and have different hashes from those that get picked when doing a clean install, which makes it hard to check for incompatibilities. With that said, could you try starting `LocalCUDACluster` with a clean, minimal conda install, e.g.:

```
conda create -n rapids -c rapidsai -c nvidia -c conda-forge -c defaults python=3.7 cudatoolkit=11.0 dask-cuda=21.10
```

If this works, it will give us a hint that some package in your environment is probably incompatible.

Disclaimer: the above code + conda environment works on my end.

**Comment by yangl57** [comment]
I have problem installing dask-cudf in your suggested environment. @pentschev 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0

Your installed version is: 2.17

**Comment by pentschev** [comment]
dask-cudf isn't necessary to test what I asked above, did that work?

But later if you're trying to install dask-cudf, make sure you install everything you need from conda as you create the environment (i.e., add `cudf=21.10 dask-cudf=21.10` to the `conda create ...` command) instead of trying to install it later, as satisfying dependencies after the environment was created is often problematic.

**Comment by yangl57** [comment]
@pentschev  Thanks. I was able to initiate the client. However, the memory is much below what I have requested. 


import os

```
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

if __name__ == '__main__':
    cluster = LocalCUDACluster(n_workers=3, threads_per_worker=1, memory_limit = '120 GiB')

    print("cluster status ",cluster.status)
    print("cluster infomarion ", cluster)
    client = Client(cluster)

    print("client information ", client)
```
It returns the following: 
```
cluster infomarion  LocalCUDACluster(a7e2a854, 'tcp://*****', workers=3, threads=3, memory=12.00 GiB)
client information  <Client: 'tcp://*****' processes=3 threads=3, memory=12.00 GiB>
```

I have three 40GB GPUs. Why does the client only claim 12 GiB out of 120 GB GPU memory?
Thanks.

**Comment by quasiben** [comment]
The `memory_limit` refers to the host memory limit per worker -- this argument is used to _limit_ the amount of memory a worker can use.   I'd recommend looking at the following docs:
https://docs.rapids.ai/api/dask-cuda/nightly/api.html#cluster

If you want to pre-allocate the memory on the GPUs you should use `rmm_pool_size` like the following:

```python
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

if __name__ == '__main__':
    cluster = LocalCUDACluster(n_workers=3, threads_per_worker=1, rmm_pool_size = '38GB')

    print("cluster status ",cluster.status)
    print("cluster infomarion ", cluster)
    client = Client(cluster)

    print("client information ", client)
```

**Comment by yangl57** [comment]
<img width="800" alt="notworking" src="https://user-images.githubusercontent.com/15113700/141208385-c167c1c3-f98a-4678-ba5e-d197518fcddd.png">

It seems like this doesn't change the host memory limit per worker to 38GB. 
I keep getting memory issues as:

```
distributed.nanny - WARNING - Restarting worker
distributed.worker - WARNING - Worker is at 91% memory usage. Pausing worker.  Process memory: 0.92 GiB -- Worker memory limit: 1.00 GiB
distributed.worker - WARNING - Unmanaged memor
```

**Comment by pentschev** [comment]
Please take a moment to read about the usage of `memory_limit`, `device_memory_limit` and `rmm_pool_size` parameters from the doc @quasiben mentioned above: https://docs.rapids.ai/api/dask-cuda/nightly/api.html#cluster .

It's not clear what you're asking for, you were mentioning GPU memory in https://github.com/rapidsai/dask-cuda/issues/773#issuecomment-964662862, thus @quasiben advised you to use `rmm_pool_size` to preallocate GPU memory. In https://github.com/rapidsai/dask-cuda/issues/773#issuecomment-965827821 you're now asking about host memory.

Printing `cluster` and `client` only presents `memory`, which is a representation of sum `memory_limit` for all workers, and `memory_limit` _per worker_ is capped at maximum system memory. From your previous comments it seems that you have only 4GB of system (host) memory, as that is the default chosen by Dask, and you were limited to 12GB total (4GB per worker, for 3 workers) when you set `memory_limit = '120 GiB'`. If you have 3 GPUs of 40GB each, but are limited to 4GB of system memory, you may really have trouble with Dask, since various parts may happen on the host, including, but not limited to, scheduling and data transfer (depending on your data source).

**Comment by yangl57** [comment]
@pentschev  It was a bit challenging for me to figure out the usage of memory_limit, device_memory_limit, and rmm_pool_size. Thanks for your help. 

Since I received some memory errors for my downstream tasks, I was trying to figure out where the memory limit was rooted from. The system memory indeed caused problems. However, I requested more than 200 GB of CPU memory on a Slurm system. I am still confused why I am only allocated a total of 12GB of system memory. 

I have a dataset of 30GB. With 4 X 40GB GPU memory, 32 CPU cores, what would be the appropriate configuration to successfully implement [XGBoost on gpus](https://developer.nvidia.com/blog/accelerating-xgboost-on-gpu-clusters-with-dask/)? 

Thanks.

**Comment by pentschev** [comment]
> I have a dataset of 30GB. With 4 X 40GB GPU memory, 32 CPU cores, what would be the appropriate configuration to successfully implement [XGBoost on gpus](https://developer.nvidia.com/blog/accelerating-xgboost-on-gpu-clusters-with-dask/)? 

Unfortunately, I have very little knowledge of XGBoost and can't make any recommendations. Maybe try asking that in https://github.com/dmlc/xgboost/issues ?
