### ISSUE TITLE
What's the best way for me to handle the GPU memory exceed issue?

### ISSUE THREAD

**Issue by Jing25** [rapidsai/dask-cuda#778]
Hi there,

I use LocalCUDACluster to create a local GPU cluster with 4 GPUs. I use dask.delayed and also tried dask.future to parallelize a very large for loop. In the loop, I load data from CPU to GPU to do some calculations. The chunk size was first set so that one GPU can only do one task at a time. So I met GPU memory error after only a few loops. Then I reduced the chunk size to 1/4, and tested with 100 tasks, it worked fine. But increasing to 400 tasks, the process became very unstable. I think this is because the GPU cannot rebalance the tasks assigned to each worker.

The following is an example of what I did:

```
def f_dask(chunks):

    result = []
    for chunk in tqdm(chunks):

        data_delayed = dask.delayed(load_onetime)(chunk)
        temp_gpu = dask.delayed(to_gpu)(data_delayed)
        ## some other processes

        arr = dask.delayed(infer)(df, model)

        output = dask.delayed(save)(arr)
        result.append(output)
        
    return result
```

`t = dask.compute(f_dask(chunks))`

Is there a way for me to, say,  lock the GPU so that before the GPU memory has been released, no new task will be assigned to a worker? I didn't find useful information on the internet, I'm if it's possible or what's the best practice to avoid the GPU memory issue in my case.

Thanks in advance!

**Comment by jakirkham** [comment]
Are you able to use [Arrays]( https://docs.dask.org/en/latest/array.html ) or [DataFrames]( https://docs.dask.org/en/latest/dataframe.html ) for your use case? They have some more sophisticated algorithms baked into them that may be more performant than building everything with `delayed`

Also might be worth reading [this blogpost on loading image data]( https://blog.dask.org/2019/06/20/load-image-data ). While it is focused on image data, the general strategy can be applied to other kinds of data. So if using `delayed` is necessary for getting data loaded, this can help move code from `delayed` into higher level objects like Arrays & DataFrames

**Comment by jakirkham** [comment]
Ofc! 😄

Dask Arrays and DataFrames do operate on chunked data. They will apply CuPy & cuDF operations within chunks. Then Dask does some higher level graph operations on top of those chunks to compute results.

Maybe this is overly simplistic, but hopefully [these slides]( https://github.com/aspp-apac/2019-parallel-python ) give you an idea of how that works? (note the environment file is out-of-date so Binder won't work unfortunately). The [Dask docs]( https://docs.dask.org/en/latest/10-minutes-to-dask.html ) go into more detail.

Guessing you already have data that is split into multiple files? So the idea would be to write operations that handle loading each file individually (perhaps with `delayed`). Convert those into Dask Arrays or Dataframes. Then join those together into a large Dask Array or DataFrame that you can operate on.

If your data is already in a format Dask [Arrays]( https://docs.dask.org/en/latest/array-api.html#create-and-store-arrays ) or [DataFrames]( https://docs.dask.org/en/latest/dataframe-create.html ) support, one can skip those steps and just use one of these APIs, which effectively do this loading & combining for you under-the-hood.

As long as the individual files themselves fit into memory, this should work. Would give that a try and if you run into issues report back with a bit more detail about what you tried & what didn't work. Sound good? 🙂

**Comment by Jing25** [comment]
Great, thank you for the information and reading materials! I'm gonna try it now

**Comment by Jing25** [comment]
Hi @jakirkham , I tried to create a dask cupy as shown below with some processes such as resize, concatenate, rechunk, etc.:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/27107288/142278527-33e358e8-16e0-42c8-be85-75d0caca3211.png">

Then I use cuml dask to do the inference on this dask array:
`cuml_model.predict_proba(X_test).compute()`

It doesn't work. I think this is now a question for cuml right?

**Comment by Jing25** [comment]
I see GPU memory exceed error again.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/27107288/142279423-9e6b8029-52e7-4b54-aa14-13366347d28a.png">

**Comment by jakirkham** [comment]
Yeah let's raise an issue on the cuML repo, @Jing25 🙂

(also feel free to cc me there)

**Comment by jakirkham** [comment]
It may be that we want to write the result directly to disk instead of using `.compute()`, which will copy the whole result over in memory to the `Client`. Another option may be `.persist()`, which computes, but keeps the results on the `Workers`

**Comment by Jing25** [comment]
Ah, good point. I should be more careful when using `.compute()`. In my case, there seem to be still some issues other than this. I'm going to close this comment and raise an issue on the cuML repo. I appreciate your help!
