### ISSUE TITLE
Failing `test_proxy.py::test_sizeof_cudf`

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#824]
I'm seeing `dask_cuda/tests/test_proxy.py::test_sizeof_cudf` failing locally:

```python
___________________________________________________ test_sizeof_cudf ____________________________________________________

    def test_sizeof_cudf():
        cudf = pytest.importorskip("cudf")
        a = cudf.datasets.timeseries().reset_index()
        a_size = sizeof(a)
        pxy = proxy_object.asproxy(a)
        assert a_size == pytest.approx(sizeof(pxy))
        pxy._pxy_serialize(serializers=("dask",))
        assert a_size == pytest.approx(sizeof(pxy))
        assert pxy._pxy_get().is_serialized()
        pxy._pxy_cache = {}
>       assert a_size == pytest.approx(sizeof(pxy))
E       assert 86832408 == 87156456 ± 8.7e+01
E         +86832408
E         -87156456 ± 8.7e+01

dask_cuda/tests/test_proxy.py:609: AssertionError
================================================ short test summary info ================================================
FAILED dask_cuda/tests/test_proxy.py::test_sizeof_cudf - assert 86832408 == 87156456 ± 8.7e+01
=========================================== 1 failed, 91 deselected in 5.19s ============================================
```

The issue above is present with the following cuDF build:

```
cudf                      22.02.00a220110 cuda_11_py38_g0d5ec7f890_245    rapidsai-nightly
dask-cudf                 22.02.00a220110 cuda_11_py38_g0d5ec7f890_245    rapidsai-nightly
libcudf                   22.02.00a220110 cuda11_g0d5ec7f890_245    rapidsai-nightly
```

But an old environment with the following passes:

```
cudf                      22.02.00a220106 cuda_11_py38_g33f7f0d032_227    rapidsai-nightly
dask-cudf                 22.02.00a220106 cuda_11_py38_g33f7f0d032_227    rapidsai-nightly
libcudf                   22.02.00a220106 cuda11_g33f7f0d032_227    rapidsai-nightly
```

@shwina @quasiben did we have any changes in cuDF that could have affected the way `sizeof` in any of its objects?

cc @madsbk

**Comment by shwina** [comment]
Yes, https://github.com/rapidsai/cudf/pull/9544.

cc @vyasr

**Comment by pentschev** [comment]
No, the one above has been taken care of via https://github.com/rapidsai/dask-cuda/pull/767 . Notice how the build that's passing above is from January 6th and https://github.com/rapidsai/cudf/pull/9544 was merged last November. It seems that the change affecting `test_proxy.py::test_sizeof_cudf` has been introduced sometime since January 6th.

**Comment by pentschev** [comment]
@madsbk it's not immediately clear whether there has been some change in cuDF that could have caused this. The closest candidate we have is https://github.com/rapidsai/rmm/pull/931, but that was merged January 5th and my January 6th build was still passing, thus I think that's not it. Given the test is checking for approximate return values, any ideas whether this could have been a change from some other `ProxyObject` dependency?
