### ISSUE TITLE
Test failure with latest distributed

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#869]
With https://github.com/dask/distributed/pull/5814/ merged in, the `test_proxify_host_file.py::test_worker_force_spill_to_disk` test currently fails test fails in due to assertion in distributed: https://github.com/dask/distributed/blob/39c5e8856cb05ad1833a0f6ee6c3fea0ddab1c1c/distributed/worker.py#L3882-L3884

self.data is `<class 'dask_cuda.proxify_host_file.ProxifyHostFile'>` and SpillBuffer is its own type.  It seems like we could either ask why the assertion is necessary or subclass spillbuffer for ProxifyHostFile

cc @madsbk

**Comment by pentschev** [comment]
Sorry, only saw this now. I believe this is a breaking change from Distributed for us, I filed https://github.com/dask/distributed/issues/5909 as well.

**Comment by jakirkham** [comment]
Think this was fixed by PR ( https://github.com/dask/distributed/pull/5904 ) included in `distributed` version `2022.03.0`. Going to go ahead and close this out, but please feel free to reopen if needed.
