### ISSUE TITLE
[Bug] host memory limit incorrectly calculated for threads_per_worker > 1

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/dask-cuda#874]
When a `LocalCUDACluster` is created with `threads_per_worker > 1` the memory_limit per worker is incorrectly computed to be `threads_per_worker * expected_value`.

If I have 8 workers and 800GB host memory, I get 100GB/worker if tpw=1, but 200GB/worker if tpw=2

**Comment by charlesbluca** [comment]
What would your expected behavior for `memory_limit` be here? It looks like this is controlled by Distributed's [`parse_memory_limit`](https://github.com/dask/distributed/blob/f0e9f8902a02bfb1af70f614c4b0ffa05cb53e6b/distributed/worker_memory.py#L334-L336), which when `memory_limit="auto"` sets the limit to be a fraction of total host memory:

```python
    if memory_limit == "auto":
        memory_limit = int(system.MEMORY_LIMIT * min(1, nthreads / total_cores))
```

**Comment by ayushdg** [comment]
I expect the `memory_limit` per worker to stay the same as we increase number of threads per worker such that the following is always true (if set to "auto"): `total_host_memory = memory_limit per worker * n_workers`.
Dask-cuda today populates the `total_cores` in the function mentioned above to `n_workers`, which doesn't satisfy the condition when `nthreads > 1`. Leading to cases where if I have 4GPUs , 400GB total system memory and 8 threads per workers, dask-cuda assigns a memory_limit of `400GB * 8 threads/4 workers` or a memory limit of 800GB per worker, a value higher than even the total memory available.

The fix should be just passing `nthreads=1` irrespective of the actual value similar to the case here:
https://github.com/dask/distributed/blob/2d3fddc14d1e06fd06b9f0f4c3256f254f3c670e/distributed/deploy/local.py#L197-L198

**Comment by madsbk** [comment]
> The fix should be just passing `nthreads=1` irrespective of the actual value similar to the case here:

Sounds like a good approach to me
