### ISSUE TITLE
Dask cuda oom error when training a ml model

### ISSUE THREAD

**Issue by Jack-Wells** [rapidsai/dask-cuda#895]
I am trying to train a ml model using dask. I am training on my local machine with 1 GPU. My GPU has 24 GiBs of memory.

```
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, LocalCluster

import dask.dataframe as dd
import pandas as pd
import numpy as np
import os
import xgboost as xgb

np.random.seed(42)


def get_columns(filename):
    return pd.read_csv(filename, nrows=10).iloc[:, :NUM_FEATURES].columns


def get_data(filename, target):
    import dask_cudf
    X = dask_cudf.read_csv(filename)
    # X = dd.read_csv(filename, assume_missing=True)
    y = X[[target]]
    X = X.iloc[:, :NUM_FEATURES]
    return X, y


def main(client: Client) -> None:
    X, y = get_data(FILENAME, TARGET)
    model = xgb.dask.DaskXGBRegressor(
        tree_method="gpu_hist",
        objective="reg:squarederror",
        seed=42,
        max_depth=5,
        eta=0.01,
        n_estimators=10)

    model.client = client
    model.fit(X, y, eval_set=[(X, y)])
    print("Saving the model..")
    model.get_booster().save_model("xgboost.model")

    print("Doing model importance..")
    columns = get_columns(FILENAME)
    pd.Series(model.feature_importances_, index=columns).sort_values(ascending=False).to_pickle("~/yolo.pkl")


if __name__ == "__main__":
    os.environ["MALLOC_TRIM_THRESHOLD_"]="65536"
    with LocalCUDACluster(device_memory_limit="15 GiB", rmm_pool_size="20 GiB") as cluster:
    # with LocalCluster() as cluster:
        with Client(cluster) as client:
            print(client)
            main(client)
```

Error as follows.

```
MemoryError: std::bad_alloc: out_of_memory: RMM failure at:/workspace/.conda-bld/work/include/rmm/mr/device/pool_memory_resource.hpp:192: Maximum pool size exceeded
```

Basically my GPU runs out of memory when I call model.fit.

I have tried fiddling around with

 - LocalCUDACluster: device_memory_limit and rmm_pool_size
 - dask_cudf.read_csv: chunksize
    

Nothing has worked.

**Comment by ayushdg** [comment]
Thanks for raising an issue @Jack-Wells! 
Are you able to share the memory needed by `X,y`? When training with xgboost, xgboost requires all the input data to be persisted in memory. This means that setting params like `chunksize` and `device_memory_limit` help with partitioning and spilling of Dask DataFrame operations such as `read_csv` but the `model.fit` step will try to persist everything in memory and then train the model. This may or may not fit based on the dataset size and available GPU memory.

**Comment by Jack-Wells** [comment]
Hi ayushdg,

Thanks for the quick response. Great to virtually meet you.

The csv file I am using to generate this error contains 128'198 rows and 4'294 columns. It is 3.6GB on disk and appears to take up 8GB in RAM when loaded via a pandas dataframe.

**Comment by Jack-Wells** [comment]
In my example code, if I replace the following

```
X = dask_cudf.read_csv(filename)
# X = dd.read_csv(filename, assume_missing=True)
```

with

```
# X = dask_cudf.read_csv(filename)
X = dd.read_csv(filename, assume_missing=True)
```

I.e. use dask.dataframe.read_csv instead of dask_cudf.read_csv, then I no longer have a memory issue and my code runs to completion successfully.

In fact with dask.dataframe.read_csv I can use a similar csv with 1'000'000 rows and 4'294 columns and my code will run to completion successfully.

For me this example highlights that I am either misusing a RAPIDS library or there's something fundamentally wrong with one of the libraries. I am a big fan of the RAPIDS ecosystem so it would be great to get to the bottom of this for the benefit of the growing community.

I am happy to jump on a call if it helps.

**Comment by pentschev** [comment]
When you use `dask.dataframe.read_csv` then you're actually doing the work on the CPU, and your system memory may suffice for that problem. I'm not sure if XGBoost will in that case also do all processing on CPU or if it will move data to the GPU, I suspect the first will be the case.

Things you may try to avoid OOM:

1. Reduce chunksize/increase number of partitions as @ayushdg mentioned;
2. Persisting the datasets -- also as mentioned by @ayushdg -- before XGBoost to know if you're running OOM before XGBoost or during, like [this](https://github.com/rapidsai/dask-cuda/blob/branch-22.06/dask_cuda/benchmarks/local_cudf_merge.py#L151);
3. Use [RMM managed memory](https://github.com/rapidsai/dask-cuda/blob/7a0c2c23e53bc11400e7cdad282df65d893635be/dask_cuda/local_cuda_cluster.py#L118-L124), in this case you would probably not need `device_memory_limit`;
4. Try using [JIT-unspill](https://docs.rapids.ai/api/dask-cuda/nightly/spilling.html#jit-unspill).

**Comment by pentschev** [comment]
This has gone stale, closing.
