### ISSUE TITLE
Less restrictive pins in release version

### ISSUE THREAD

**Issue by ntabris** [rapidsai/dask-cuda#911]
The current release of dask-cuda is pinned to dask/distributed 2022.03.0.

There's a merged PR to unpin these "for development" (https://github.com/rapidsai/dask-cuda/pull/892) which implies that they're going to be pinned again for release.

Is there a reason for the exact pinning? The PR that pinned these (https://github.com/rapidsai/dask-cuda/pull/878) says it's to be in line with cuDF and the PR that pinned for cuDF gave no reason.

**Comment by pentschev** [comment]
Yes, Dask provides no API guarantees. Dask-CUDA is the backbone of RAPIDS and just allowing Dask-CUDA release package to pick the latest Dask/Distributed is guaranteed to be a source of problem after a few (or even just one) release. Therefore we need to pin to a version that we test and is known to work.

Before every RAPIDS release we decide what Dask/Distributed release is stable and pin that version, which we then unpin when we begin working on the new branch for the upcoming RAPIDS release.

**Comment by pentschev** [comment]
We have a discussion about this in https://github.com/rapidsai/dask-cuda/issues/848 as well.

**Comment by pentschev** [comment]
Given this isn't something we are likely to change due to the reasons in https://github.com/rapidsai/dask-cuda/issues/911#issuecomment-1130019748 and since there has been no further discussions, I'm closing this issue. Please feel free to reopen if needed.
