### ISSUE TITLE
Spill quickly from device to host

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cuda#92]
I'm curious how fast we are at moving data back and forth between device and host memory.  I suspect that currently we end up serializing with standard Dask serialization, which may not be aware of device memory.  We should take a look at using the `"cuda"` serialization family within Dask, that was added as part of the UCX work.   

```python
from distributed.protocol import serialize, deserialize
x = cupy.arange(100)
header, frames = serialize(x, serializers=("cuda", "dask", "pickle"))
y = deserialize(header, frames, deserializers=("cuda", "dask", "pickle",    "error"))
```

(more here https://github.com/dask/distributed/tree/master/distributed/protocol/tests)

And then we should probably do a bit of profiling.  I would focus this on just the `DeviceHostDisk` class, rather than engaging the full dask.distributed cluster machinery.

This is relevant for a couple of applications that people care about today

1.  Larger than memory image processing (a bit)
2.  Out-of-core sorts and joins (cc @randerzander @kkraus14) (more relevant)

@pentschev , you seem like the obvious person to work on this if you have some time.  I think it'd be useful to know how fast we are today, then look at serialization with the new "cuda" Dask serializer, and then see how fast we can get things relative to theoretical hardware speeds.

**Comment by pentschev** [comment]
Yes, I haven't done any profiling, and I'm sure this is something that could be improved. Thanks for pointing me to the CUDA serialization, I wasn't aware of that specialization.

If the is not of utmost urgency, I can take a look at this next week, this week I'm mostly busy with EuroPython presentation and at the conference.

**Comment by mrocklin** [comment]
Alrighty, I think that we can probably wait until next week (although @randerzander please jump in if not).  Enjoy the conference !

**Comment by pentschev** [comment]
I did some quick benchmarking:

```python
In [1]: import cupy

In [2]: from distributed.protocol import serialize, deserialize

In [3]: x = cupy.arange(1.25e8)

In [4]: %%timeit
   ...: y = serialize(x)
   ...:
   ...:
1.73 s ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: x.nbytes / 1.73 / 1e6
Out[5]: 578.0346820809249

In [6]: %%timeit
   ...: y = serialize(serialize(x, serializers=("cuda", "dask", "pickle")))
   ...:
   ...:
1.77 s ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]: x.nbytes / 1.77 / 1e6
Out[7]: 564.9717514124293
```

The way we serialize nowadays (in [4]) does roughly 576MB/s, whereas the suggested here does 565MB/s. The new way is slightly slower, and both are _very_ slow. Copying data back to CPU in form of a NumPy array is faster, about 2GB/s:

```python
In [8]: %%timeit
   ...: y = x.get()
   ...:
   ...:
494 ms ± 639 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]: x.nbytes / .494 / 1e6
Out[9]: 2024.2914979757086
```

From my experience, we should be able to get about 6GB/s for copying data from GPU to CPU, or 12GB/s when using pinned memory (which I'm not sure we can do with CuPy under all circumstances).

I suspect serialization adds a considerable overhead, but 2GB/s feels still too slow, Numba seems to give us similar performance:

```python
In [1]: import numpy as np

In [2]: from numba import cuda

In [3]: x = np.arange(1.25e8)

In [4]: d_x = cuda.to_device(x)

In [5]: %%timeit
   ...: d_x.copy_to_host()
   ...:
   ...:
514 ms ± 1.41 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: 1e9 / .514 / 1e6
Out[6]: 1945.5252918287938
```

I'm not yet sure how we can improve any of those numbers, but I'll investigate further.

**Comment by pentschev** [comment]
Serializing a NumPy array takes 1.11 s:

```python
In [1]: import numpy as np

In [2]: from distributed.protocol import serialize, deserialize

In [3]: x = np.arange(1.25e8)

In [4]: %%timeit
   ...: y = serialize(x)
   ...:
   ...:
9.26 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]: %%timeit
   ...: y = serialize(serialize(x))
   ...:
   ...:
1.11 s ± 448 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

If we split the CuPy copy (from my previous comment, 494 ms) and serialization (1.11 s), we get 1.604 s, almost the same as we do for serializing a CuPy array (1.73 s in my previous comment). Therefore, pickling dominates the serialization. Are there faster ways for pickling data in Python? Since the arrays are basically just a bunch of bytes anyway (assuming we don't need to transpose the array, etc.), I'm a bit surprised that it's so slow.

**Comment by mrocklin** [comment]
Should this

```python
y = serialize(serialize(x))
```
Instead be this?

```python
y = deserialize(*serialize(x, serializers=...), serializers=...)
```
 
I would expect to call serialize to get header and frames, and then move those into host memory and write them to disk

```python
header, frames = serialize(x, serializers=["cuda", "dask", "pickle", "msgpack"])
frames = [ensure_on_host(frame) for frame in frames]
```

**Comment by pentschev** [comment]
> `header, frames = serialize(x, serializers=["cuda", "dask", "pickle", "msgpack"])`

This basically just creates a header and wraps the array `x` in a list, but doesn't really serialize anything. The second `serialize` call actually pickles the array, and that's what I wanted to time. In other words, calling `serialize` once, doesn't really do anything, thus it's really fast.

**Comment by mrocklin** [comment]
I see.  I suspect that things will be a bit faster if we move each device-side bytes object to a host-side-bytes object independently, rather than bundle them up into a single bytes-like object with serialize/pickle.

**Comment by pentschev** [comment]
The things is that both copying data back to host and pickling are slow. Pickling still dominates, so that should probably be the first one to improve, but the outlook of copying memory back from device is not so good either.

**Comment by mrocklin** [comment]
Right, mostly I'm trying to separate overhead from using pickle relative to using whatever numba to/from_device function there is, and also trying to remove the overhead of concatenating all of the results together when we pickle the list.  

Then, once we have a nice number that uses pure numba operations (which it looks like you have above already) we can ask the Numba devs.  Given that this is already the case, maybe we should raise an issue there and ask for help?  I suspect that they have run into this before and can help.

**Comment by pentschev** [comment]
> Right, mostly I'm trying to separate overhead from using pickle relative to using whatever numba to/from_device function there is, and also trying to remove the overhead of concatenating all of the results together when we pickle the list.

The list is a single element, unlike the NumPy implementation, the CuPy one is not creating views of the object to break them down into various blocks. Doing that may help pickling (if that can be done in parallel), but copying will likely perform poorly.

> Then, once we have a nice number that uses pure numba operations (which it looks like you have above already) we can ask the Numba devs. Given that this is already the case, maybe we should raise an issue there and ask for help? I suspect that they have run into this before and can help.

I can do that, but I will first write a small C++ sample to illustrate that and make sure I have numbers for the same machine and compare apples to apples.

**Comment by mrocklin** [comment]
@pentschev can I ask you to quickly try an implementation that looks like the following:

```python
def _serialize_if_device(obj):
    """ Serialize an object if it's a device object """
    assert is_device_object(obj)  # this used to be a conditional, under what situations would this not be a device object?
    header, frames = cuda_serialize(obj)
    frames = [numba.DeviceArray(frame).copy_to_host() for frame in frames]
    return header, frames

def _deserialize_if_device(obj):
    header, frames = obj
    frames = [numba.cuda.to_device(frame) for frame in frames]
    return cuda_deserialize(header, frames)
```
    
Previously these functions would check to see if the object was device-like.  Why this condition?  Was this for things like lists and dicts?  If so, lets just implement `cuda_serialize` operations for lists and dicts that concatenate the headers and frames of their inputs as necessary.
