### ISSUE TITLE
Upgrade to Dask `2022.05.2` before RAPIDS 22.06

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#921]
With the Dask `2022.05.1` release there were a few issues that got introduced and are being fixed with a new `2022.05.2` release planned for today/tomorrow, see https://github.com/dask/community/issues/250 for details.

Some of those issues are critical for RAPIDS and even though we just moved the pin to `2022.05.1` yesterday, we will need to move it again to the new release once it's out.

@galipremsagar if you have the chance and will to go over this again, could I ask you to take care of this?

@jakirkham @quasiben @charlesbluca FYI

**Comment by galipremsagar** [comment]
> @galipremsagar if you have the chance and will to go over this again, could I ask you to take care of this?

Sure, will take care of this Peter.

**Comment by jakirkham** [comment]
Yeah discussed this with Prem earlier offline

**Comment by jakirkham** [comment]
Not at all. Agreed. Also good to have this tracked in an issue :)

**Comment by galipremsagar** [comment]
Resolved by: https://github.com/rapidsai/dask-cuda/pull/922
